//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMPresentation.App_Start {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlatMensagens_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlatMensagens_Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrecificacaoPresentation.App_Start.PlatMensagens_Resources", typeof(PlatMensagens_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail invalido.
        /// </summary>
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login não cadastrado.
        /// </summary>
        internal static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario esta inativo.
        /// </summary>
        internal static string M0003 {
            get {
                return ResourceManager.GetString("M0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario esta bloqueado. Entre em contato com o administrador do sistema para executar o desbloqueio.
        /// </summary>
        internal static string M0004 {
            get {
                return ResourceManager.GetString("M0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario ja efetuou um login com a senha provisoria. Favor gerar outra senha.
        /// </summary>
        internal static string M0005 {
            get {
                return ResourceManager.GetString("M0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero de falhas de login superior ao limite diario de falhas.
        /// </summary>
        internal static string M0006 {
            get {
                return ResourceManager.GetString("M0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credenciais invalidas.
        /// </summary>
        internal static string M0007 {
            get {
                return ResourceManager.GetString("M0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha nao pode ser igual a anterior.
        /// </summary>
        internal static string M0008 {
            get {
                return ResourceManager.GetString("M0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha nao foi confirmada corretamente.
        /// </summary>
        internal static string M0009 {
            get {
                return ResourceManager.GetString("M0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem acesso a essa funcionalidade.
        /// </summary>
        internal static string M0011 {
            get {
                return ResourceManager.GetString("M0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário cadastrado mas sem acesso ao sistema. Consulte a administração..
        /// </summary>
        internal static string M0012 {
            get {
                return ResourceManager.GetString("M0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro atendeu ao filtro especificado.
        /// </summary>
        internal static string M0016 {
            get {
                return ResourceManager.GetString("M0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum arquivo selecionado.
        /// </summary>
        internal static string M0019 {
            get {
                return ResourceManager.GetString("M0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extensão de arquivo não suportada.
        /// </summary>
        internal static string M0020 {
            get {
                return ResourceManager.GetString("M0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato já cadastrado.
        /// </summary>
        internal static string M0021 {
            get {
                return ResourceManager.GetString("M0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do arquivo muito longo.
        /// </summary>
        internal static string M0024 {
            get {
                return ResourceManager.GetString("M0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo já cadastrado.
        /// </summary>
        internal static string M0025 {
            get {
                return ResourceManager.GetString("M0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O texto da mensagem deve ser preenchido.
        /// </summary>
        internal static string M0026 {
            get {
                return ResourceManager.GetString("M0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato já incluído neste grupo.
        /// </summary>
        internal static string M0027 {
            get {
                return ResourceManager.GetString("M0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de Contato já cadastrada.
        /// </summary>
        internal static string M0028 {
            get {
                return ResourceManager.GetString("M0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir essa categoria. Existem informações vinculadas a ela.
        /// </summary>
        internal static string M0029 {
            get {
                return ResourceManager.GetString("M0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status de Contato já cadastrado.
        /// </summary>
        internal static string M0030 {
            get {
                return ResourceManager.GetString("M0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse status de contato. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0031 {
            get {
                return ResourceManager.GetString("M0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrão de Mensagem já cadastrado.
        /// </summary>
        internal static string M0032 {
            get {
                return ResourceManager.GetString("M0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse status de contato. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0033 {
            get {
                return ResourceManager.GetString("M0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrada de CRM criada a partir de mensagem.
        /// </summary>
        internal static string M0034 {
            get {
                return ResourceManager.GetString("M0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um processo com o mesmo nome para este usuário.
        /// </summary>
        internal static string M0035 {
            get {
                return ResourceManager.GetString("M0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse processo. Existem ações ainda pendentes..
        /// </summary>
        internal static string M0036 {
            get {
                return ResourceManager.GetString("M0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de cancelamento não pode ser inferior a data de criação do processo.
        /// </summary>
        internal static string M0037 {
            get {
                return ResourceManager.GetString("M0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de cancelamento não pode ser superior a data corrente.
        /// </summary>
        internal static string M0038 {
            get {
                return ResourceManager.GetString("M0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um contato marcado como PRINCIPAL.
        /// </summary>
        internal static string M0039 {
            get {
                return ResourceManager.GetString("M0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir nova ação. Já existe uma ação ativa neste momento..
        /// </summary>
        internal static string M0040 {
            get {
                return ResourceManager.GetString("M0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível editar esta ação. Ela está encerrada ou excluída..
        /// </summary>
        internal static string M0041 {
            get {
                return ResourceManager.GetString("M0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível criar/reativar esta ação. Já existe uma ação ativa neste momento..
        /// </summary>
        internal static string M0042 {
            get {
                return ResourceManager.GetString("M0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de encerramento não pode ser inferior a data de criação.
        /// </summary>
        internal static string M0043 {
            get {
                return ResourceManager.GetString("M0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário já cadastrado.
        /// </summary>
        internal static string M0044 {
            get {
                return ResourceManager.GetString("M0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse usuário. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0045 {
            get {
                return ResourceManager.GetString("M0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de encerramento não pode ser superior a data corrente.
        /// </summary>
        internal static string M0046 {
            get {
                return ResourceManager.GetString("M0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de cancelamento não pode ser inferior a data de criação.
        /// </summary>
        internal static string M0047 {
            get {
                return ResourceManager.GetString("M0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de cancelamento não pode ser superior a data corrente.
        /// </summary>
        internal static string M0048 {
            get {
                return ResourceManager.GetString("M0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano já cadastrado.
        /// </summary>
        internal static string M0049 {
            get {
                return ResourceManager.GetString("M0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse Plano. Existem assinantes vinculados a ele.
        /// </summary>
        internal static string M0050 {
            get {
                return ResourceManager.GetString("M0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar usuário. Número de usuários ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0051 {
            get {
                return ResourceManager.GetString("M0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar contato. Número de contatos ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0052 {
            get {
                return ResourceManager.GetString("M0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível enviar este e-mail. O número de e-mails enviados no mês corrente ultrapassa o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0053 {
            get {
                return ResourceManager.GetString("M0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível enviar este SMS. O número de SMSs enviados no mês corrente ultrapassa o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0054 {
            get {
                return ResourceManager.GetString("M0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar processos. Número de processos ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0055 {
            get {
                return ResourceManager.GetString("M0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar ações nos processos. Número de ações ativas excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0056 {
            get {
                return ResourceManager.GetString("M0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assinante já cadastrado.
        /// </summary>
        internal static string M0057 {
            get {
                return ResourceManager.GetString("M0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filial já cadastrada.
        /// </summary>
        internal static string M0058 {
            get {
                return ResourceManager.GetString("M0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir essa Filial. Existem informações vinculadas a ela.
        /// </summary>
        internal static string M0059 {
            get {
                return ResourceManager.GetString("M0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deve ser especificado um arquivo template HTML ou o corpo da mensagem.
        /// </summary>
        internal static string M0060 {
            get {
                return ResourceManager.GetString("M0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corpo de mansagem especificado sem cabeçalho e área de dados (rodapé).
        /// </summary>
        internal static string M0061 {
            get {
                return ResourceManager.GetString("M0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum filtro foi definido para montagem do grupo..
        /// </summary>
        internal static string M0062 {
            get {
                return ResourceManager.GetString("M0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum contato obedeceu ao filtro especificado.
        /// </summary>
        internal static string M0063 {
            get {
                return ResourceManager.GetString("M0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este plano de assinatura não tem acesso às funcionalidades de CRM.
        /// </summary>
        internal static string M0064 {
            get {
                return ResourceManager.GetString("M0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Essa mensagem já foi convertida em processo CRM.
        /// </summary>
        internal static string M0065 {
            get {
                return ResourceManager.GetString("M0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria já cadastrada.
        /// </summary>
        internal static string M0066 {
            get {
                return ResourceManager.GetString("M0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo já cadastrado.
        /// </summary>
        internal static string M0067 {
            get {
                return ResourceManager.GetString("M0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este cargo. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0068 {
            get {
                return ResourceManager.GetString("M0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta categoria. Ela está vinculada a outras informações.
        /// </summary>
        internal static string M0069 {
            get {
                return ResourceManager.GetString("M0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Origem do processo CRM já cadastrada.
        /// </summary>
        internal static string M0070 {
            get {
                return ResourceManager.GetString("M0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta origem. Ela está vinculada a outras informações.
        /// </summary>
        internal static string M0071 {
            get {
                return ResourceManager.GetString("M0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo de Cancelameneto já cadastrado.
        /// </summary>
        internal static string M0072 {
            get {
                return ResourceManager.GetString("M0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Senha não pode ficar em branco.
        /// </summary>
        internal static string M0073 {
            get {
                return ResourceManager.GetString("M0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova senha não pode ser em branco.
        /// </summary>
        internal static string M0074 {
            get {
                return ResourceManager.GetString("M0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação da senha não pode ser em branco.
        /// </summary>
        internal static string M0075 {
            get {
                return ResourceManager.GetString("M0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este motivo. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0076 {
            get {
                return ResourceManager.GetString("M0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo de Encerramento já cadastrado.
        /// </summary>
        internal static string M0077 {
            get {
                return ResourceManager.GetString("M0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Ação já cadastrado.
        /// </summary>
        internal static string M0078 {
            get {
                return ResourceManager.GetString("M0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este tipo. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0079 {
            get {
                return ResourceManager.GetString("M0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar cliente. Número de clientes ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0080 {
            get {
                return ResourceManager.GetString("M0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar fornecedor. Número de fornecedores ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0081 {
            get {
                return ResourceManager.GetString("M0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de Equipamento já cadastrada.
        /// </summary>
        internal static string M0082 {
            get {
                return ResourceManager.GetString("M0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de Fornecedor já cadastrada.
        /// </summary>
        internal static string M0083 {
            get {
                return ResourceManager.GetString("M0083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor residual não pode ser maior que o valor de compra.
        /// </summary>
        internal static string M0084 {
            get {
                return ResourceManager.GetString("M0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar produto. Número de produtos ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0085 {
            get {
                return ResourceManager.GetString("M0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este produto. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0086 {
            get {
                return ResourceManager.GetString("M0086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este produto. Ele está vinculado a um ou mais pedidos de venda.
        /// </summary>
        internal static string M0087 {
            get {
                return ResourceManager.GetString("M0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de Produto já cadastrada.
        /// </summary>
        internal static string M0088 {
            get {
                return ResourceManager.GetString("M0088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Subcategoria de Produto já cadastrada.
        /// </summary>
        internal static string M0089 {
            get {
                return ResourceManager.GetString("M0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta subcategoria. Ela está vinculada a outras informações.
        /// </summary>
        internal static string M0090 {
            get {
                return ResourceManager.GetString("M0090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho já cadastrado.
        /// </summary>
        internal static string M0091 {
            get {
                return ResourceManager.GetString("M0091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este tamanho. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0092 {
            get {
                return ResourceManager.GetString("M0092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unidade já cadastrada.
        /// </summary>
        internal static string M0093 {
            get {
                return ResourceManager.GetString("M0093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta unidade. Ela está vinculada a outras informações.
        /// </summary>
        internal static string M0094 {
            get {
                return ResourceManager.GetString("M0094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-Mail não cadastrado..
        /// </summary>
        internal static string M0096 {
            get {
                return ResourceManager.GetString("M0096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O login não pode ficar em branco.
        /// </summary>
        internal static string M0109 {
            get {
                return ResourceManager.GetString("M0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-Mail já existente.
        /// </summary>
        internal static string M0110 {
            get {
                return ResourceManager.GetString("M0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login já existente.
        /// </summary>
        internal static string M0111 {
            get {
                return ResourceManager.GetString("M0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar atendimentos. Número de atendimentos ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0112 {
            get {
                return ResourceManager.GetString("M0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definição de automação de mensagens já cadastrada.
        /// </summary>
        internal static string M0113 {
            get {
                return ResourceManager.GetString("M0113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este grupo. Ele está vinculaoa a outras informações.
        /// </summary>
        internal static string M0114 {
            get {
                return ResourceManager.GetString("M0114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo já cadastrado.
        /// </summary>
        internal static string M0115 {
            get {
                return ResourceManager.GetString("M0115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este subgrupo. Ele está vinculaoa a outras informações.
        /// </summary>
        internal static string M0116 {
            get {
                return ResourceManager.GetString("M0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Subgrupo já cadastrado.
        /// </summary>
        internal static string M0117 {
            get {
                return ResourceManager.GetString("M0117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar ordens de serviço. Número de ordens de serviço ativas excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0118 {
            get {
                return ResourceManager.GetString("M0118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Justificativa de cancelamento não preenchida.
        /// </summary>
        internal static string M0119 {
            get {
                return ResourceManager.GetString("M0119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Departamento já cadastrado.
        /// </summary>
        internal static string M0120 {
            get {
                return ResourceManager.GetString("M0120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este departamento. Ele está vinculada a outras informações.
        /// </summary>
        internal static string M0121 {
            get {
                return ResourceManager.GetString("M0121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível criar/reativar esta proposta. Já existe uma proposta sendo processada neste momento..
        /// </summary>
        internal static string M0122 {
            get {
                return ResourceManager.GetString("M0122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível editar esta proposta. Ela está encerrada, cancelada ou reprovada.
        /// </summary>
        internal static string M0123 {
            get {
                return ResourceManager.GetString("M0123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A justificativa do cancelamento é obrigatória.
        /// </summary>
        internal static string M0124 {
            get {
                return ResourceManager.GetString("M0124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de cancelamento não informada.
        /// </summary>
        internal static string M0125 {
            get {
                return ResourceManager.GetString("M0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de reprovação não pode ser inferior a data de criação do processo.
        /// </summary>
        internal static string M0126 {
            get {
                return ResourceManager.GetString("M0126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de reprovação não pode ser superior a data corrente.
        /// </summary>
        internal static string M0127 {
            get {
                return ResourceManager.GetString("M0127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A justificativa da reprovação é obrigatória.
        /// </summary>
        internal static string M0128 {
            get {
                return ResourceManager.GetString("M0128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de reprovação não informada.
        /// </summary>
        internal static string M0129 {
            get {
                return ResourceManager.GetString("M0129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de aprovação não pode ser inferior a data de criação do processo.
        /// </summary>
        internal static string M0130 {
            get {
                return ResourceManager.GetString("M0130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de aprovação não pode ser superior a data corrente.
        /// </summary>
        internal static string M0131 {
            get {
                return ResourceManager.GetString("M0131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A justificativa da aprovação é obrigatória.
        /// </summary>
        internal static string M0132 {
            get {
                return ResourceManager.GetString("M0132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de aprovação não informada.
        /// </summary>
        internal static string M0133 {
            get {
                return ResourceManager.GetString("M0133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de envio não informada.
        /// </summary>
        internal static string M0134 {
            get {
                return ResourceManager.GetString("M0134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de envio não pode ser inferior a data de criação do processo.
        /// </summary>
        internal static string M0135 {
            get {
                return ResourceManager.GetString("M0135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de envio não pode ser superior a data corrente.
        /// </summary>
        internal static string M0136 {
            get {
                return ResourceManager.GetString("M0136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu erro no envio da proposta por e-mail.
        /// </summary>
        internal static string M0137 {
            get {
                return ResourceManager.GetString("M0137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível enviar. Nenhum arquivo anexado a essa proposta.
        /// </summary>
        internal static string M0138 {
            get {
                return ResourceManager.GetString("M0138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum template de mensagem selecionado.
        /// </summary>
        internal static string M0139 {
            get {
                return ResourceManager.GetString("M0139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível criar/reativar este pedido. Já existe um pedido sendo processado neste momento..
        /// </summary>
        internal static string M0140 {
            get {
                return ResourceManager.GetString("M0140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente não especificado.
        /// </summary>
        internal static string M0141 {
            get {
                return ResourceManager.GetString("M0141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de ação não especificado.
        /// </summary>
        internal static string M0142 {
            get {
                return ResourceManager.GetString("M0142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Responsável pela ação não especificado.
        /// </summary>
        internal static string M0143 {
            get {
                return ResourceManager.GetString("M0143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Template de proposta não especificado.
        /// </summary>
        internal static string M0144 {
            get {
                return ResourceManager.GetString("M0144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo de cancelamento não especificado.
        /// </summary>
        internal static string M0145 {
            get {
                return ResourceManager.GetString("M0145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transportadora não especificada.
        /// </summary>
        internal static string M0146 {
            get {
                return ResourceManager.GetString("M0146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data prevista para entrega não especificada.
        /// </summary>
        internal static string M0147 {
            get {
                return ResourceManager.GetString("M0147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de saida para entrega não especificada.
        /// </summary>
        internal static string M0148 {
            get {
                return ResourceManager.GetString("M0148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do Motivo de cancelamento não especificada.
        /// </summary>
        internal static string M0149 {
            get {
                return ResourceManager.GetString("M0149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maquina de cartão já cadastrada.
        /// </summary>
        internal static string M0150 {
            get {
                return ResourceManager.GetString("M0150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta máqiuna de cartão. Existem registros vinculados a ela..
        /// </summary>
        internal static string M0151 {
            get {
                return ResourceManager.GetString("M0151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plataforma de Entregas já cadastrada.
        /// </summary>
        internal static string M0152 {
            get {
                return ResourceManager.GetString("M0152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta plataforma de entregas. Existem registros vinculados a ela..
        /// </summary>
        internal static string M0153 {
            get {
                return ResourceManager.GetString("M0153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo já cadastrado.
        /// </summary>
        internal static string M0154 {
            get {
                return ResourceManager.GetString("M0154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este cargo. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0155 {
            get {
                return ResourceManager.GetString("M0155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa Externa já cadastrada.
        /// </summary>
        internal static string M0156 {
            get {
                return ResourceManager.GetString("M0156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta pessoa externa. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0157 {
            get {
                return ResourceManager.GetString("M0157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF já existente na lista de usuários.
        /// </summary>
        internal static string M0158 {
            get {
                return ResourceManager.GetString("M0158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo já cadastrado.
        /// </summary>
        internal static string M0159 {
            get {
                return ResourceManager.GetString("M0159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este grupo. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0160 {
            get {
                return ResourceManager.GetString("M0160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Subgrupo já cadastrado.
        /// </summary>
        internal static string M0161 {
            get {
                return ResourceManager.GetString("M0161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este subgrupo. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0162 {
            get {
                return ResourceManager.GetString("M0162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta já cadastrada no Plano de Contas.
        /// </summary>
        internal static string M0163 {
            get {
                return ResourceManager.GetString("M0163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta conta do plano de contas. Existem registros vinculados a ela..
        /// </summary>
        internal static string M0164 {
            get {
                return ResourceManager.GetString("M0164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Banco já cadastrado.
        /// </summary>
        internal static string M0165 {
            get {
                return ResourceManager.GetString("M0165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este banco. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0166 {
            get {
                return ResourceManager.GetString("M0166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta bancária já cadastrada.
        /// </summary>
        internal static string M0167 {
            get {
                return ResourceManager.GetString("M0167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma conta marcada como principal.
        /// </summary>
        internal static string M0168 {
            get {
                return ResourceManager.GetString("M0168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum lançamento cadastrado nessa conta.
        /// </summary>
        internal static string M0169 {
            get {
                return ResourceManager.GetString("M0169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor já cadastrado.
        /// </summary>
        internal static string M0170 {
            get {
                return ResourceManager.GetString("M0170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este fornecedor. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0171 {
            get {
                return ResourceManager.GetString("M0171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forma de Pagamento/Recebimento já cadastrada.
        /// </summary>
        internal static string M0172 {
            get {
                return ResourceManager.GetString("M0172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta Forma de Pagamento/Recebomento. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0173 {
            get {
                return ResourceManager.GetString("M0173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente já cadastrado.
        /// </summary>
        internal static string M0174 {
            get {
                return ResourceManager.GetString("M0174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este cliente. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0175 {
            get {
                return ResourceManager.GetString("M0175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de cliente já cadastrada.
        /// </summary>
        internal static string M0176 {
            get {
                return ResourceManager.GetString("M0176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta categoria. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0177 {
            get {
                return ResourceManager.GetString("M0177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de fornecedor já cadastrada.
        /// </summary>
        internal static string M0178 {
            get {
                return ResourceManager.GetString("M0178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta categoria. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0179 {
            get {
                return ResourceManager.GetString("M0179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Máquina de cartão já associada à empresa.
        /// </summary>
        internal static string M0180 {
            get {
                return ResourceManager.GetString("M0180", resourceCulture);
            }
        }
    }
}
