//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACESSO_SITE
    {
        public int ACST_CD_ID { get; set; }
        public System.DateTime ACST_DT_ACESSO { get; set; }
        public string ACST_IP_IP { get; set; }
        public string ACST_NM_CIDADE { get; set; }
        public string ACST_NM_UF { get; set; }
        public string ACST_NM_PAIS { get; set; }
        public string ACST_NM_PROVEDOR { get; set; }
        public Nullable<int> ACST_IN_ATIVO { get; set; }
    }
}
