//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACESSO_METODO
    {
        public int ACES_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> ACES_DT_ACESSO { get; set; }
        public string ACES_SG_ACESSO { get; set; }
        public string ACES_NM_CONTROLLER { get; set; }
        public string ACES_NM_METHOD { get; set; }
        public Nullable<int> PACI_CD_ID { get; set; }
        public Nullable<int> PAAM_CD_ID { get; set; }
        public Nullable<int> PAAT_CD_ID { get; set; }
        public Nullable<int> PACO_CD_ID { get; set; }
        public Nullable<int> PAEX_CD_ID { get; set; }
        public Nullable<int> PAEF_CD_ID { get; set; }
        public Nullable<int> PAPR_CD_ID { get; set; }
        public Nullable<int> PASO_CD_ID { get; set; }
        public Nullable<int> USUT_CD_ID { get; set; }
        public Nullable<int> ASST_CD_ID { get; set; }
        public Nullable<int> AVIS_CD_ID { get; set; }
        public Nullable<int> MEDI_CD_ID { get; set; }
        public Nullable<int> MENS__CD_ID { get; set; }
        public Nullable<int> PERF_CD_ID { get; set; }
        public Nullable<int> SOLI_CD_ID { get; set; }
        public Nullable<int> TEEM_CD_ID { get; set; }
        public Nullable<int> TSMS_CD_ID { get; set; }
        public int ACES_IN_ATIVO { get; set; }
        public Nullable<int> ACES_IN_SISTEMA { get; set; }
        public Nullable<System.DateTime> ACES_DT_DUMMY { get; set; }
        public string ACES_IP_IP_LOGIN { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual ASSINANTE ASSINANTE1 { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
