//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENDA()
        {
            this.AGENDA_ANEXO = new HashSet<AGENDA_ANEXO>();
            this.AGENDA_CONTATO = new HashSet<AGENDA_CONTATO>();
            this.AGENDA_VINCULO = new HashSet<AGENDA_VINCULO>();
            this.ATENDIMENTO_AGENDA = new HashSet<ATENDIMENTO_AGENDA>();
            this.DIARIO_COMPRA = new HashSet<DIARIO_COMPRA>();
            this.DIARIO_PROCESSO = new HashSet<DIARIO_PROCESSO>();
            this.ORDEM_SERVICO_AGENDA = new HashSet<ORDEM_SERVICO_AGENDA>();
        }
    
        public int AGEN_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> EMPR_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> CAAG_CD_ID { get; set; }
        public Nullable<int> CRM1_CD_ID { get; set; }
        public Nullable<int> TARE_CD_ID { get; set; }
        public Nullable<int> PACI_CD_ID { get; set; }
        public Nullable<int> CRAC_CD_ID { get; set; }
        public System.DateTime AGEN_DT_DATA { get; set; }
        public System.TimeSpan AGEN_HR_HORA { get; set; }
        public Nullable<System.TimeSpan> AGEN_HR_FINAL { get; set; }
        public string AGEN_NM_TITULO { get; set; }
        public string AGEN_DS_DESCRICAO { get; set; }
        public int AGEN_IN_ATIVO { get; set; }
        public Nullable<int> AGEN_CD_USUARIO { get; set; }
        public string AGEN_TX_OBSERVACOES { get; set; }
        public Nullable<int> AGEN_IN_STATUS { get; set; }
        public Nullable<int> AGEN_IN_CORPORATIVA { get; set; }
        public string AGEN_LK_REUNIAO { get; set; }
        public Nullable<int> AGEN_IN_CONFIRMADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENDA_ANEXO> AGENDA_ANEXO { get; set; }
        public virtual CATEGORIA_AGENDA CATEGORIA_AGENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENDA_CONTATO> AGENDA_CONTATO { get; set; }
        public virtual CRM CRM { get; set; }
        public virtual CRM_ACAO CRM_ACAO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENDA_VINCULO> AGENDA_VINCULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENDIMENTO_AGENDA> ATENDIMENTO_AGENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIARIO_COMPRA> DIARIO_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIARIO_PROCESSO> DIARIO_PROCESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO_AGENDA> ORDEM_SERVICO_AGENDA { get; set; }
    }
}
