//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSINANTE_PLANO
    {
        public int ASPL_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int PLAN_CD_ID { get; set; }
        public int ASPL_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> ASPL_DT_INICIO { get; set; }
        public Nullable<System.DateTime> ASPL_DT_VALIDADE { get; set; }
        public Nullable<int> ASPL_IN_PRECO { get; set; }
        public Nullable<int> ASPL_IN_SISTEMA { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual PLANO PLANO { get; set; }
    }
}
