//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSINANTE_PLANO_ASSINATURA
    {
        public int ASPA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int PLAS_CD_ID { get; set; }
        public int ASPA_IN_ATIVO { get; set; }
        public System.DateTime ASPA_DT_INICIO { get; set; }
        public System.DateTime ASPA_DT_VALIDADE { get; set; }
        public int ASPA_IN_PRECO { get; set; }
        public int ASPA_IN_SISTEMA { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual PLANO_ASSINATURA PLANO_ASSINATURA { get; set; }
    }
}
