//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSINANTE_PAGAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSINANTE_PAGAMENTO()
        {
            this.ASSINANTE_PAGAMENTO_ANEXO = new HashSet<ASSINANTE_PAGAMENTO_ANEXO>();
        }
    
        public int ASPA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> PLAN_CD_ID { get; set; }
        public Nullable<int> ASPA_IN_SISTEMA { get; set; }
        public Nullable<System.DateTime> ASPA_DT_PAGAMENTO { get; set; }
        public Nullable<decimal> ASPA_VL_VALOR { get; set; }
        public Nullable<System.DateTime> ASPA_DT_PROXIMO { get; set; }
        public Nullable<int> ASPA_IN_PAGO { get; set; }
        public Nullable<System.DateTime> ASPA_DT_VENCIMENTO { get; set; }
        public Nullable<int> ASPA_NR_ATRASO { get; set; }
        public Nullable<decimal> ASPA_VL_VALOR_PAGO { get; set; }
        public Nullable<int> ASPA_IN_ATIVO { get; set; }
        public Nullable<int> ASPA_IN_INFORMADO { get; set; }
        public Nullable<int> PLAS_CD_ID { get; set; }
        public Nullable<int> ASPA_IN_TIPO { get; set; }
        public Nullable<System.DateTime> ASPA_DT_INFORMA { get; set; }
        public string ASPA_DS_INFORMACOES { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSINANTE_PAGAMENTO_ANEXO> ASSINANTE_PAGAMENTO_ANEXO { get; set; }
        public virtual PLANO PLANO { get; set; }
        public virtual PLANO_ASSINATURA PLANO_ASSINATURA { get; set; }
    }
}
