//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENDIMENTO_PROPOSTA_ACOMPANHAMENTO
    {
        public int ATPA_CD_ID { get; set; }
        public int ATPR_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> ATPA_DT_ACOMPANHAMENTO { get; set; }
        public string ATPA_TX_ACOMPANHAMENTO { get; set; }
        public int ATPA_IN_ATIVO { get; set; }
    
        public virtual ATENDIMENTO_PROPOSTA ATENDIMENTO_PROPOSTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
