//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENDIMENTO_ACOMPANHAMENTO
    {
        public int ATAC_CD_ID { get; set; }
        public int ATEN_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public string ATAC_DS_ACOMPANHAMENTO { get; set; }
        public int ATAC_IN_ATIVO { get; set; }
        public System.DateTime ATAC_DT_ACOMPANHAMENTO { get; set; }
        public Nullable<System.DateTime> ATAC_DT_ENCERRAMENTO { get; set; }
        public string ATAC_DS_ENCERRAMENTO { get; set; }
    
        public virtual ATENDIMENTO ATENDIMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
