//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENDIMENTO_PROPOSTA_SERVICO
    {
        public int ATPS_CD_ID { get; set; }
        public int ATPR_CD_ID { get; set; }
        public int SERV_CD_ID { get; set; }
        public int ATPS_NR_QUANTIDADE { get; set; }
        public int ATPS_IN_ATIVO { get; set; }
    
        public virtual ATENDIMENTO_PROPOSTA ATENDIMENTO_PROPOSTA { get; set; }
        public virtual SERVICO SERVICO { get; set; }
    }
}
