//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CONHECIMENTO
    {
        public int BACO_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> BACO_IN_SISTEMA { get; set; }
        public string BACO_NM_NOME { get; set; }
        public Nullable<System.DateTime> BACO_DT_ENTRADA { get; set; }
        public Nullable<System.DateTime> BACO_DT_VALIDADE { get; set; }
        public string BACO_AQ_ARQUIVO { get; set; }
        public Nullable<int> BACO_IN_ATIVO { get; set; }
        public Nullable<int> BACO_IN_TIPO { get; set; }
    }
}
