//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA_ATENDIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA_ATENDIMENTO()
        {
            this.ATENDIMENTO = new HashSet<ATENDIMENTO>();
        }
    
        public int CAAT_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string CAAT_NM_NOME { get; set; }
        public int CAAT_IN_ATIVO { get; set; }
        public Nullable<int> CAAT_IN_SLA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENDIMENTO> ATENDIMENTO { get; set; }
    }
}
