//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA_CLIENTE()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.GRUPO = new HashSet<GRUPO>();
        }
    
        public int CACL_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public string CACL_NM_NOME { get; set; }
        public Nullable<int> CACL_IN_LIMITE_MINIMO_EMITIDAS { get; set; }
        public Nullable<int> CACL_IN_LIMITE_MAXIMO_EMITIDAS { get; set; }
        public Nullable<int> CACL_IN_LIMITE_MINIMO_APROVADAS { get; set; }
        public Nullable<int> CACL_IN_LIMITE__MAXIMO_APROVADAS { get; set; }
        public Nullable<int> CACL_IN_LIMITE_MINIMO_REPROVADAS { get; set; }
        public Nullable<int> CACL_IN_LIMITE__MAXIMO_REPROVADAS { get; set; }
        public Nullable<int> CACL_IN_ORDEM { get; set; }
        public Nullable<int> CACL_IN_ATIVO { get; set; }
        public Nullable<int> CACL_IN_FIXO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO> GRUPO { get; set; }
    }
}
