//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_CONTATO
    {
        public int CLCO_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public string CLCO_NM_NOME { get; set; }
        public string CLCO_NM_CARGO { get; set; }
        public string CLCO_NM_EMAIL { get; set; }
        public string CLCO_NM_TELEFONE { get; set; }
        public string CLCO_DS_OBSERVACOES { get; set; }
        public int CLCO_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
