//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_QUADRO_SOCIETARIO
    {
        public int CLQS_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public string CLQS_NM_QUALIFICACAO { get; set; }
        public string CLQS_NM_PAIS_ORIGEM { get; set; }
        public string CLQS_NM_REPRESENTANTE_LEGAL { get; set; }
        public string CLQS_NM_QUALIFICACAO_REP_LEGAL { get; set; }
        public string CLQS_NM_NOME { get; set; }
        public Nullable<int> CLQS_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
