//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA_CONTATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA_CONTATO()
        {
            this.MENSAGENS_ENVIADAS_SISTEMA = new HashSet<MENSAGENS_ENVIADAS_SISTEMA>();
        }
    
        public int COCO_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int COMP_CD_ID { get; set; }
        public string COC_NM_NOME { get; set; }
        public string COCO_NR_TELEFONE { get; set; }
        public string COCO_NR_CELULAR { get; set; }
        public string COCO_NM_EMAIL { get; set; }
        public string COCO_NM_CARGO { get; set; }
        public Nullable<int> COCO_IN_PRINCIPAL { get; set; }
        public Nullable<int> COCO_IN_ATIVO { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGENS_ENVIADAS_SISTEMA> MENSAGENS_ENVIADAS_SISTEMA { get; set; }
    }
}
