//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA_ANOTACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA_ANOTACAO()
        {
            this.DIARIO_COMPRA = new HashSet<DIARIO_COMPRA>();
        }
    
        public int COAT_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int COMP_CD_ID { get; set; }
        public System.DateTime COAT_DT_ANOTACAO { get; set; }
        public int USUA_CD_ID { get; set; }
        public string COAT_DS_ANOTACAO { get; set; }
        public int COAT_IN_ATIVO { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIARIO_COMPRA> DIARIO_COMPRA { get; set; }
    }
}
