//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA_FORNECEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA_FORNECEDOR()
        {
            this.COMPRA_FORNECEDOR_ITEM = new HashSet<COMPRA_FORNECEDOR_ITEM>();
        }
    
        public int COFO_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int COMP_CD_ID { get; set; }
        public int FORN_CD_ID { get; set; }
        public Nullable<System.DateTime> COFO_DT_ENVIO { get; set; }
        public Nullable<System.DateTime> COFO_DT_RESPOSTA { get; set; }
        public int COFO_IN_ATIVO { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_FORNECEDOR_ITEM> COMPRA_FORNECEDOR_ITEM { get; set; }
    }
}
