//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACAO_CALENDARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONFIGURACAO_CALENDARIO()
        {
            this.CONFIGURACAO_CALENDARIO_BLOQUEIO = new HashSet<CONFIGURACAO_CALENDARIO_BLOQUEIO>();
        }
    
        public int COCA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> COCA_IN_ATIVO { get; set; }
        public Nullable<int> COCA_IN_SEGUNDA_FEIRA { get; set; }
        public Nullable<int> COCA_IN_TERCA_FEIRA { get; set; }
        public Nullable<int> COCA_IN_QUARTA_FEIRA { get; set; }
        public Nullable<int> COCA_IN_QUINTA_FEIRA { get; set; }
        public Nullable<int> COCA_IN_SEXTA_FEIRA { get; set; }
        public Nullable<int> COCA_IN_SABADO { get; set; }
        public Nullable<int> COCA_IN_DOMINGO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_SEG_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_SEG_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_TER_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_TER_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_QUA_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_QUA_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_QUI_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_QUI_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_SEX_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_SEX_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_SAB_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_SAB_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_DOM_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_COMERCIAL_DOM_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_SEG_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_SEG_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_TER_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_QUA_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_QUI_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_SEX_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_SAB_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_DOM_INICIO { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_TER_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_QUA_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_QUI_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_SEX_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_SAB_FINAL { get; set; }
        public Nullable<System.TimeSpan> COCA_HR_INTERVALO_DOM_FINAL { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFIGURACAO_CALENDARIO_BLOQUEIO> CONFIGURACAO_CALENDARIO_BLOQUEIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
