//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA_PAGAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONSULTA_PAGAMENTO()
        {
            this.PAGAMENTO_ANEXO = new HashSet<PAGAMENTO_ANEXO>();
            this.PAGAMENTO_ANOTACAO = new HashSet<PAGAMENTO_ANOTACAO>();
            this.PAGAMENTO_NOTA_FISCAL = new HashSet<PAGAMENTO_NOTA_FISCAL>();
            this.MOVIMENTO_ESTOQUE_PRODUTO = new HashSet<MOVIMENTO_ESTOQUE_PRODUTO>();
        }
    
        public int COPA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> TIPA_CD_ID { get; set; }
        public Nullable<System.DateTime> COPA_DT_PAGAMENTO { get; set; }
        public Nullable<decimal> COPA_VL_VALOR { get; set; }
        public Nullable<int> COPA_IN_CONFERIDO { get; set; }
        public int COPA_IN_ATIVO { get; set; }
        public string COPA_NM_NOME { get; set; }
        public Nullable<System.DateTime> COPA_DT_DUMMY { get; set; }
        public string COPA_GU_GUID { get; set; }
        public string COPA_XM_NOTA_FISCAL { get; set; }
        public string COPA_NM_FAVORECIDO { get; set; }
        public Nullable<System.DateTime> COPA_DT_VENCIMENTO { get; set; }
        public Nullable<int> COPA_IN_PAGO { get; set; }
        public Nullable<decimal> COPA_VL_DESCONTO { get; set; }
        public Nullable<decimal> COPA_VL_MULTA { get; set; }
        public Nullable<decimal> COPA_VL_PAGO { get; set; }
        public Nullable<int> COPA_NR_ATRASO { get; set; }
        public Nullable<System.DateTime> COPA_DT_CADASTRO { get; set; }
    
        public virtual TIPO_PAGAMENTO TIPO_PAGAMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGAMENTO_ANEXO> PAGAMENTO_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGAMENTO_ANOTACAO> PAGAMENTO_ANOTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGAMENTO_NOTA_FISCAL> PAGAMENTO_NOTA_FISCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMENTO_ESTOQUE_PRODUTO> MOVIMENTO_ESTOQUE_PRODUTO { get; set; }
    }
}
