//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_PAGAR_FALHA
    {
        public int CPFA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public string CPFA_NR_DOCUMENTO { get; set; }
        public string CPFA_NM_NOME { get; set; }
        public string CPFA_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> CLFA_DT_VENCIMENTO { get; set; }
        public Nullable<System.DateTime> CLFA_DT_DATA { get; set; }
        public Nullable<System.DateTime> CLFA_DT_DUMMY { get; set; }
        public string CLFA_DS_MOTIVO { get; set; }
        public Nullable<int> CLFA_IN_SISTEMA { get; set; }
        public Nullable<int> CPFA_IN_NUMERO { get; set; }
        public string CPFA_NM_INFO { get; set; }
        public Nullable<int> EMFI_CD_ID { get; set; }
    
        public virtual EMPRESA_FILIAL EMPRESA_FILIAL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
