//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_RECEBER_ANEXO
    {
        public int CRAN_CD_ID { get; set; }
        public int CARE_CD_ID { get; set; }
        public string CRAN_NM_TITULO { get; set; }
        public System.DateTime CRAN_DT_ANEXO { get; set; }
        public int CRAN_IN_TIPO { get; set; }
        public string CRAN_AQ_ARQUIVO { get; set; }
        public int CRAN_IN_ATIVO { get; set; }
    
        public virtual CONTA_RECEBER CONTA_RECEBER { get; set; }
    }
}
