//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_BANCO_CONTATO
    {
        public int CBCT_CD_ID { get; set; }
        public int COBA_CD_ID { get; set; }
        public string CBCT_NM_NOME { get; set; }
        public string CBCT_NM_EMAIL { get; set; }
        public string CBCT_NM_CARGO { get; set; }
        public string CBCT_NR_TELEFONES { get; set; }
        public int CBCT_IN_ATIVO { get; set; }
        public string CBCT_NR_CELULAR { get; set; }
    
        public virtual CONTA_BANCO CONTA_BANCO { get; set; }
    }
}
