//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PEDIDO_VENDA_ACOMPANHAMENTO
    {
        public int CRPC_CD_ID { get; set; }
        public int CRPV_CD_ID { get; set; }
        public System.DateTime CRPC_DT_ACOMPANHAMENTO { get; set; }
        public int USUA_CD_ID { get; set; }
        public string CRPC_TX_ACOMPANHAMENTO { get; set; }
        public int CRPC_IN_ATIVO { get; set; }
    
        public virtual CRM_PEDIDO_VENDA CRM_PEDIDO_VENDA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
