//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PEDIDO_ENVIO
    {
        public int CRPE_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> CRPV_CD_ID { get; set; }
        public Nullable<int> TRAN_CD_ID { get; set; }
        public Nullable<int> CRPE_IN_TIPO_ENVIO { get; set; }
        public Nullable<System.DateTime> CRPE_DT_CONTATO { get; set; }
        public string CRPE_NR_CORREIO { get; set; }
        public Nullable<System.DateTime> CRPE_DT_POSTAGEM { get; set; }
        public string CRPE_NM_RESPONSAVEL { get; set; }
        public Nullable<int> CRPE_IN_ENTREGA_PESSOAL { get; set; }
        public string CRPE_NM_PORTADOR { get; set; }
        public Nullable<System.DateTime> CRPE_DT_ENVIO { get; set; }
        public Nullable<int> CRPE_IN_ENVIADO { get; set; }
        public Nullable<int> CRPE_IN_ENTREGA { get; set; }
        public Nullable<System.DateTime> CRPE_DT_ENTREGA { get; set; }
        public string CRPE_NM_RECEBEDOR { get; set; }
        public Nullable<int> CRPE_IN_MOTIVO_FALHA { get; set; }
        public string CRPE_NM_MOTIVO_FALHA { get; set; }
        public Nullable<int> CRPE_IN_NOVO_CRIADO { get; set; }
        public Nullable<int> CRPE_IN_ATIVO { get; set; }
    
        public virtual CRM_PEDIDO_VENDA CRM_PEDIDO_VENDA { get; set; }
        public virtual TRANSPORTADORA TRANSPORTADORA { get; set; }
    }
}
