//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PEDIDO_VENDA_ITEM_SERVICO
    {
        public int CPVS_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int CRPV_CD_ID { get; set; }
        public int SERV_CD_ID { get; set; }
        public Nullable<int> SERV1_CD_ID { get; set; }
        public Nullable<int> EMFI_CD_ID { get; set; }
        public Nullable<decimal> CPVS_VL_VALOR { get; set; }
        public Nullable<decimal> CPVS_VL_PROMOCAO { get; set; }
        public Nullable<decimal> CPVS_PC_DESCONTO { get; set; }
        public Nullable<int> CPVS_QN_QUANTIDADE { get; set; }
        public Nullable<int> CPVS_IN_ATIVO { get; set; }
        public Nullable<decimal> CPVS_VL_VENDA { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public string CPVS_NM_UNIDADE { get; set; }
        public Nullable<decimal> CPVS_VL_TOTAL { get; set; }
        public Nullable<int> CPVS_IN_EXPRESSO { get; set; }
        public Nullable<int> CPVS_IN_DURACAO { get; set; }
        public Nullable<decimal> CPVS_VL_PECAS { get; set; }
    
        public virtual CRM_PEDIDO_VENDA CRM_PEDIDO_VENDA { get; set; }
        public virtual EMPRESA_FILIAL EMPRESA_FILIAL { get; set; }
        public virtual SERVICO SERVICO { get; set; }
        public virtual SERVICOS SERVICOS { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
    }
}
