//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_PEDIDO_VENDA_ITEM
    {
        public int CPVI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int CRPV_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public Nullable<int> EMFI_CD_ID { get; set; }
        public Nullable<decimal> CPVI_VL_VALOR { get; set; }
        public Nullable<decimal> CPVI_VL_PROMOCAO { get; set; }
        public Nullable<decimal> CPVI_PC_DESCONTO { get; set; }
        public Nullable<int> CPVI_QN_QUANTIDADE { get; set; }
        public Nullable<int> CPVI_IN_ESTOQUE { get; set; }
        public Nullable<int> CPVI_IN_ATIVO { get; set; }
        public Nullable<decimal> CPVI_VL_VENDA { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public string CPVI_NM_UNIDADE { get; set; }
        public Nullable<decimal> CPVI_VL_TOTAL { get; set; }
        public Nullable<int> CPVI_IN_PRECO { get; set; }
    
        public virtual CRM_PEDIDO_VENDA CRM_PEDIDO_VENDA { get; set; }
        public virtual EMPRESA_FILIAL EMPRESA_FILIAL { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
    }
}
