//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTO_FIXO_CALENDARIO
    {
        public int CFCD_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> CAPA_CD_ID { get; set; }
        public int CUFX_CD_ID { get; set; }
        public System.DateTime CFCD_DT_VENCIMENTO { get; set; }
        public int CFCD_IN_ATIVO { get; set; }
    
        public virtual CONTA_PAGAR CONTA_PAGAR { get; set; }
        public virtual CUSTO_FIXO CUSTO_FIXO { get; set; }
    }
}
