//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIARIO_COMPRA
    {
        public int CODR_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<int> COMP_CD_ID { get; set; }
        public Nullable<int> COAT_CD_ID { get; set; }
        public Nullable<int> AGEN__CD_ID { get; set; }
        public Nullable<System.DateTime> CODR_DT_DATA { get; set; }
        public string CODR_NM_OPERACAO { get; set; }
        public string CODR_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> CODR_DT_DUMMY { get; set; }
        public Nullable<System.DateTime> CODR_DT_DUMMY_1 { get; set; }
        public Nullable<int> EMPR_CD_ID { get; set; }
    
        public virtual AGENDA AGENDA { get; set; }
        public virtual COMPRA COMPRA { get; set; }
        public virtual COMPRA_ANOTACAO COMPRA_ANOTACAO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
