//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_AGENDAMENTO
    {
        public int EMAG_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public Nullable<int> MENS_CD_ID { get; set; }
        public Nullable<System.DateTime> EMAG_DT_AGENDAMENTO { get; set; }
        public int EMAG_IN_ENVIADO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual MENSAGENS MENSAGENS { get; set; }
    }
}
