//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA_ANEXO
    {
        public int EMAN_CD_ID { get; set; }
        public int EMPR_CD_ID { get; set; }
        public string EMAN_NM_TITULO { get; set; }
        public int EMAN_IN_TIPO { get; set; }
        public System.DateTime EMAN_DT_ANEXO { get; set; }
        public string EMAN_AQ_ARQUIVO { get; set; }
        public int EMAN_IN_ATIVO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
