//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA_CUSTO_VARIAVEL
    {
        public int EMCV_CD_ID { get; set; }
        public Nullable<int> EMPR_CD_ID { get; set; }
        public Nullable<int> PLEN_CD_ID { get; set; }
        public Nullable<int> MAQN_CD_ID { get; set; }
        public Nullable<int> TICK_CD_ID { get; set; }
        public string EMCV_NM_NOME { get; set; }
        public Nullable<decimal> EMCV_VL_VALOR { get; set; }
        public Nullable<int> EMCV_PC_PERCENTUAL_VENDA { get; set; }
        public Nullable<decimal> EMCV_PC_TAXA { get; set; }
        public Nullable<int> EMCV_IN_VENDA { get; set; }
        public Nullable<int> EMCV_IN_TIPO { get; set; }
        public Nullable<int> EMCV_IN_ATIVO { get; set; }
        public Nullable<decimal> EMCV_PC_PERCENTUAL_VENDA_DECIMAL { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual MAQUINA MAQUINA { get; set; }
        public virtual PLATAFORMA_ENTREGA PLATAFORMA_ENTREGA { get; set; }
        public virtual TICKET_ALIMENTACAO TICKET_ALIMENTACAO { get; set; }
    }
}
