//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESPECIALIDADE()
        {
            this.USUARIO = new HashSet<USUARIO>();
            this.MEDICOS = new HashSet<MEDICOS>();
            this.MEDICO_ENVIO_INFORMACAO = new HashSet<MEDICO_ENVIO_INFORMACAO>();
        }
    
        public int ESPE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string ESPE_NM_NOME { get; set; }
        public int ESPE_IN_ATIVO { get; set; }
        public Nullable<int> ESPE_IN_NIVEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICOS> MEDICOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICO_ENVIO_INFORMACAO> MEDICO_ENVIO_INFORMACAO { get; set; }
    }
}
