//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_RECEBIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMA_RECEBIMENTO()
        {
            this.CONSULTA_RECEBIMENTO = new HashSet<CONSULTA_RECEBIMENTO>();
        }
    
        public int FORE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public string FORE_NM_FORMA { get; set; }
        public int FORE_IN_ATIVO { get; set; }
        public Nullable<int> FORE_IN_PADRAO { get; set; }
        public Nullable<int> FORE_IN_FIXO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTA_RECEBIMENTO> CONSULTA_RECEBIMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
