//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR_CONTATO
    {
        public int FOCO_CD_ID { get; set; }
        public int FORN_CD_ID { get; set; }
        public string FOCO_NM_NOME { get; set; }
        public string FOCO_NM_CARGO { get; set; }
        public string FOCO_NM_EMAIL { get; set; }
        public string FOCO_NR_TELEFONES { get; set; }
        public int FOCO_IN_ATIVO { get; set; }
        public string FOCO_NR_TELEFONE { get; set; }
    
        public virtual FORNECEDOR FORNECEDOR { get; set; }
    }
}
