//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNIL()
        {
            this.CRM = new HashSet<CRM>();
            this.FUNIL_ETAPA = new HashSet<FUNIL_ETAPA>();
        }
    
        public int FUNI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> FUNI_IN_TIPO { get; set; }
        public string FUNI_NM_NOME { get; set; }
        public string FUNI_SG_SIGLA { get; set; }
        public string FUNI_DS_DESCRICAO { get; set; }
        public Nullable<int> FUNI_IN_ACOES { get; set; }
        public Nullable<int> FUNI_IN_CONTATO { get; set; }
        public Nullable<int> FUNI_IN_PROPOSTA { get; set; }
        public Nullable<int> FUNI_IN_AGENDA { get; set; }
        public System.DateTime FUNI_DT_CADASTRO { get; set; }
        public Nullable<int> FUNI_IN_FIXO { get; set; }
        public Nullable<int> FUNI_IN_CLIENTE { get; set; }
        public Nullable<int> FUNI_IN_RESPONSAVEL { get; set; }
        public int FUNI_IN_ATIVO { get; set; }
        public Nullable<int> FUNI_IN_SISTEMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM> CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUNIL_ETAPA> FUNIL_ETAPA { get; set; }
    }
}
