//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNIL_ETAPA
    {
        public int FUET_CD_ID { get; set; }
        public int FUNI_CD_ID { get; set; }
        public string FUET_NM_NOME { get; set; }
        public string FUET_SG_SIGLA { get; set; }
        public string FUET_DS_DESCRICAO { get; set; }
        public Nullable<int> FUET_IN_ORDEM { get; set; }
        public int FUET_IN_ENCERRA { get; set; }
        public Nullable<int> FUET_IN_PROPOSTA { get; set; }
        public Nullable<int> FUET_IN_EMAIL { get; set; }
        public Nullable<int> FUET_IN_SMS { get; set; }
        public Nullable<int> FUET_IN_FATURAMENTO { get; set; }
        public Nullable<int> FUET_IN_EXPEDICAO { get; set; }
        public int FUET_IN_ATIVO { get; set; }
    
        public virtual FUNIL FUNIL { get; set; }
    }
}
