//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRAU_PARENTESCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRAU_PARENTESCO()
        {
            this.PACIENTE_CONTATO = new HashSet<PACIENTE_CONTATO>();
        }
    
        public int GRPA_CD_ID { get; set; }
        public string GRPA_NM_NOME { get; set; }
        public Nullable<int> GRPA_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_CONTATO> PACIENTE_CONTATO { get; set; }
    }
}
