//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRUPO()
        {
            this.GRUPO_CLIENTE = new HashSet<GRUPO_CLIENTE>();
            this.MENSAGEM_AUTOMACAO = new HashSet<MENSAGEM_AUTOMACAO>();
            this.MENSAGENS_DESTINOS = new HashSet<MENSAGENS_DESTINOS>();
            this.MENSAGENS = new HashSet<MENSAGENS>();
            this.PESQUISA = new HashSet<PESQUISA>();
        }
    
        public int GRUP_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> EMPR_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> EMFI_CD_ID { get; set; }
        public Nullable<int> CACL_CD_ID { get; set; }
        public Nullable<int> SEXO_CD_ID { get; set; }
        public string GRUP_NM_NOME { get; set; }
        public System.DateTime GRUP_DT_CADASTRO { get; set; }
        public int GRUP_IN_ATIVO { get; set; }
        public string GRUP_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public Nullable<System.DateTime> GRUP_DT_NASCIMENTO { get; set; }
        public string GRUP_NR_DIA { get; set; }
        public string GRUP_NR_MES { get; set; }
        public string GRUP_NR_ANO { get; set; }
    
        public virtual CATEGORIA_CLIENTE CATEGORIA_CLIENTE { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual EMPRESA_FILIAL EMPRESA_FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO_CLIENTE> GRUPO_CLIENTE { get; set; }
        public virtual SEXO SEXO { get; set; }
        public virtual UF UF { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGEM_AUTOMACAO> MENSAGEM_AUTOMACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGENS_DESTINOS> MENSAGENS_DESTINOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGENS> MENSAGENS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA> PESQUISA { get; set; }
    }
}
