//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDICACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INDICACAO()
        {
            this.INDICACAO_ACAO = new HashSet<INDICACAO_ACAO>();
            this.INDICACAO_ANEXO = new HashSet<INDICACAO_ANEXO>();
        }
    
        public int INDI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> INDI_DT_DATA { get; set; }
        public string INDI_NM_INDICADO { get; set; }
        public string INDI_NM_EMAIL { get; set; }
        public string INDI_TX_MENSAGEM { get; set; }
        public int INDI_IN_ATIVO { get; set; }
        public string INDI_GU_IDENTIFICADOR { get; set; }
        public Nullable<int> INDI_IN_STATUS { get; set; }
        public Nullable<System.DateTime> INDI_DT_DESFECHO { get; set; }
        public Nullable<System.DateTime> INDI_DT_PAGAMENTO { get; set; }
        public Nullable<int> INDI_IN_PAGAMENTO { get; set; }
        public Nullable<int> INDI_IN_SISTEMA { get; set; }
        public string INDI_NR_TELEFONE { get; set; }
        public string INDI_NR_CELULAR { get; set; }
        public string INDI_DS_JUSTIFICATIVA { get; set; }
        public Nullable<System.DateTime> INDI_DT_ATUALIZACAO { get; set; }
        public string INDI_DS_ENCERRAMENTO { get; set; }
        public Nullable<decimal> INDI_VL_PAGAMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INDICACAO_ACAO> INDICACAO_ACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INDICACAO_ANEXO> INDICACAO_ANEXO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
