//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABORATORIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LABORATORIO()
        {
            this.PACIENTE_EXAMES = new HashSet<PACIENTE_EXAMES>();
            this.AREA_PACIENTE = new HashSet<AREA_PACIENTE>();
        }
    
        public int LABS_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string LABS_NM_NOME { get; set; }
        public string LABS_LK_LINK { get; set; }
        public string LABS_LK_LINK_PESSOAL { get; set; }
        public string LABS_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public int LABS_IN_ATIVO { get; set; }
    
        public virtual UF UF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_EXAMES> PACIENTE_EXAMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AREA_PACIENTE> AREA_PACIENTE { get; set; }
    }
}
