//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAD_CRM_ACAO
    {
        public int LCAC_CD_ID { get; set; }
        public int LECR_CD_ID { get; set; }
        public Nullable<System.DateTime> LCAC_DT_CRIACAO { get; set; }
        public Nullable<int> USUA_CD_ID1 { get; set; }
        public Nullable<int> USUA_CD_ID2 { get; set; }
        public string LCAC_NM_TITULO { get; set; }
        public string LCAC_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> LCAC_DT_PREVISTA { get; set; }
        public Nullable<int> TIAC_CD_ID { get; set; }
        public Nullable<int> LCAC_IN_STATUS { get; set; }
        public Nullable<int> LCAC_IN_ATIVO { get; set; }
        public Nullable<int> LCAC_NR_ATRASO { get; set; }
    
        public virtual LEAD_CRM LEAD_CRM { get; set; }
        public virtual TIPO_ACAO TIPO_ACAO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
