//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LEAD()
        {
            this.LEAD_ANEXO = new HashSet<LEAD_ANEXO>();
            this.LEAD_ANOTACAO = new HashSet<LEAD_ANOTACAO>();
            this.LEAD_CRM = new HashSet<LEAD_CRM>();
        }
    
        public int LEAD_CD_ID { get; set; }
        public Nullable<System.DateTime> LEAD_DT_ENTRADA { get; set; }
        public string LEAD_NM_NOME { get; set; }
        public string LEAD_EM_EMAIL { get; set; }
        public string LEAD_NR_CELULAR { get; set; }
        public Nullable<int> LEAD_IN_STATUS { get; set; }
        public string LEAD_NR_CPF { get; set; }
        public string LEAD_NR_CNPJ { get; set; }
        public Nullable<System.DateTime> LEAD_DT_NASCIMENTO { get; set; }
        public Nullable<int> SEXO_CD_ID { get; set; }
        public Nullable<int> LEAD_IN_SISTEMA { get; set; }
        public string LEAD_NM_ENDERECO { get; set; }
        public string LEAD_NR_NUMERO { get; set; }
        public string LEAD_NM_COMPLEMENTO { get; set; }
        public string LEAD_NM_BAIRRO { get; set; }
        public string LEAD_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string LEAD_NR_CEP { get; set; }
        public Nullable<int> LEAD_IN_ATIVO { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAD_ANEXO> LEAD_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAD_ANOTACAO> LEAD_ANOTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAD_CRM> LEAD_CRM { get; set; }
        public virtual SEXO SEXO { get; set; }
        public virtual UF UF { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
