//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAD_CRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LEAD_CRM()
        {
            this.LEAD_CRM_ACAO = new HashSet<LEAD_CRM_ACAO>();
            this.LEAD_CRM_ANEXO = new HashSet<LEAD_CRM_ANEXO>();
            this.LEAD_CRM_ANOTACAO = new HashSet<LEAD_CRM_ANOTACAO>();
        }
    
        public int LECR_CD_ID { get; set; }
        public int LEAD_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> MOCA_CD_ID { get; set; }
        public Nullable<int> CROR_CD_ID { get; set; }
        public string LECR_GU_GUID { get; set; }
        public Nullable<int> LECR_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> LECR_DT_CRIACAO { get; set; }
        public string LECR_NM_NOME { get; set; }
        public string LECR_DS_DESCRICAO { get; set; }
        public Nullable<int> LECR_IN_STATUS { get; set; }
        public Nullable<System.DateTime> LECR_DT_CANCELAMENTO { get; set; }
        public string LECR_DS_MOTIVO_CANCELAMENTO { get; set; }
        public Nullable<System.DateTime> LECR_DT_ENCERRAMENTO { get; set; }
        public string LECR_DS_INFORMACAO_ENCERRAMENTO { get; set; }
        public Nullable<int> LECR_IN_ESTRELA { get; set; }
        public Nullable<int> LECR_NR_TEMPERATURA { get; set; }
        public string LECR_NM_CAMPANHA { get; set; }
        public string LECR_DS_MOVIMENTACAO { get; set; }
        public Nullable<int> LECR_IN_SISTEMA { get; set; }
    
        public virtual CRM_ORIGEM CRM_ORIGEM { get; set; }
        public virtual LEAD LEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAD_CRM_ACAO> LEAD_CRM_ACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAD_CRM_ANEXO> LEAD_CRM_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEAD_CRM_ANOTACAO> LEAD_CRM_ANOTACAO { get; set; }
        public virtual MOTIVO_CANCELAMENTO MOTIVO_CANCELAMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
