//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAD_ANEXO
    {
        public int LEAX_CD_ID { get; set; }
        public int LEAD_CD_ID { get; set; }
        public Nullable<System.DateTime> LEAX_DT_ANEXO { get; set; }
        public string LEAX_NM_TITULO { get; set; }
        public Nullable<int> LEAX_IN_TIPO { get; set; }
        public string LEAX_AQ_ARQUIVO { get; set; }
        public Nullable<int> LEAX_IN_ATIVO { get; set; }
    
        public virtual LEAD LEAD { get; set; }
    }
}
