//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCACAO_HISTORICO
    {
        public int LOHI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int LOCA_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<int> TIHI_CD_ID { get; set; }
        public Nullable<System.DateTime> LOHI_DT_HISTORICO { get; set; }
        public string LOHI_DS_DESCRICAO { get; set; }
        public int LOHI_IN_ATIVO { get; set; }
        public string LOHI_NM_OPERACAO { get; set; }
        public Nullable<int> LOHI_IN_PACIENTE_DUMMY { get; set; }
        public Nullable<System.DateTime> LOHI_DT_DUMMY { get; set; }
    
        public virtual LOCACAO LOCACAO { get; set; }
        public virtual TIPO_HISTORICO TIPO_HISTORICO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
