//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCACAO()
        {
            this.LOCACAO_ANEXO = new HashSet<LOCACAO_ANEXO>();
            this.LOCACAO_ANOTACAO = new HashSet<LOCACAO_ANOTACAO>();
            this.LOCACAO_HISTORICO = new HashSet<LOCACAO_HISTORICO>();
            this.LOCACAO_PARCELA = new HashSet<LOCACAO_PARCELA>();
            this.LOCACAO_OCORRENCIA = new HashSet<LOCACAO_OCORRENCIA>();
        }
    
        public int LOCA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int PACI_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public int PETA_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> LOCA_DT_INICIO { get; set; }
        public Nullable<int> LOCA_NR_PRAZO { get; set; }
        public Nullable<int> LOCA_IN_QUANTIDADE { get; set; }
        public Nullable<decimal> LOCA_VL_PARCELA { get; set; }
        public Nullable<int> LOCA_IN_RENOVACAO { get; set; }
        public Nullable<int> LOCA_IN_ATIVO { get; set; }
        public Nullable<int> LOCA_IN_ENCERRADO { get; set; }
        public Nullable<decimal> LOCA_VL_TOTAL { get; set; }
        public string LOCA_GU_GUID { get; set; }
        public Nullable<int> LOCA_IN_STATUS { get; set; }
        public string LOCA_NR_NUMERO { get; set; }
        public string LOCA_NM_TITULO { get; set; }
        public string LOCA_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> LOCA_DT_DUMMY { get; set; }
        public Nullable<int> LOCA_NR_DIA { get; set; }
        public string LOCA_NM_PACIENTE_DUMMY { get; set; }
        public string LOCA_NM_PRODUTO_DUMMY { get; set; }
        public Nullable<System.DateTime> LOCA_DT_CANCELAMENTO { get; set; }
        public string LOCA_DS_JUSTIFICATIVA { get; set; }
        public Nullable<System.DateTime> LOCA_DT_ENCERRAMENTO { get; set; }
        public Nullable<System.DateTime> LOCA_DT_FINAL { get; set; }
        public Nullable<int> LOCA_NR_ATRASO { get; set; }
        public Nullable<System.DateTime> LOCA_DT_RENOVACAO { get; set; }
        public Nullable<int> LOCA_IN_RENOVACOES { get; set; }
        public string LOCA_NR_SERIE { get; set; }
        public Nullable<int> LOCA_IN_GARANTIA { get; set; }
        public Nullable<System.DateTime> LOCA_DT_GARANTIA { get; set; }
        public Nullable<System.DateTime> LOCA_DT_APROVACAO { get; set; }
        public Nullable<int> LOCA_IN_CONTRATO { get; set; }
        public string LOCA_XM_NOTA_FISCAL { get; set; }
        public Nullable<int> LOCA_NR_GARANTIA { get; set; }
        public string LOCA_TK_TOKEN { get; set; }
        public string LOCA_AQ_ARQUIVO_QRCODE { get; set; }
        public Nullable<System.DateTime> LOCA_DT_EMISSAO { get; set; }
        public Nullable<int> LOCA_IN_ASSINADO_DIGITAL { get; set; }
        public Nullable<decimal> LOCA_VL_VALOR_ATRASO { get; set; }
        public Nullable<int> LOCA_IN_ESTOQUE { get; set; }
        public Nullable<System.DateTime> LOCA_DT_ENTREGA { get; set; }
        public string LOCA_DS_ENTREGA { get; set; }
        public string LOCA_DS_ENCERRA { get; set; }
        public Nullable<int> COLO_CD_ID { get; set; }
        public Nullable<int> LOCA_CD_DISTRATO_ID { get; set; }
        public Nullable<int> LOCA_CD_ENCERRA_ID { get; set; }
        public Nullable<int> LOCA_IN_CONTRATO_ASSINA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCACAO_ANEXO> LOCACAO_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCACAO_ANOTACAO> LOCACAO_ANOTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCACAO_HISTORICO> LOCACAO_HISTORICO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCACAO_PARCELA> LOCACAO_PARCELA { get; set; }
        public virtual PERIODICIDADE_TAREFA PERIODICIDADE_TAREFA { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCACAO_OCORRENCIA> LOCACAO_OCORRENCIA { get; set; }
        public virtual CONTRATO_LOCACAO CONTRATO_LOCACAO { get; set; }
        public virtual CONTRATO_LOCACAO CONTRATO_LOCACAO1 { get; set; }
        public virtual CONTRATO_LOCACAO CONTRATO_LOCACAO2 { get; set; }
    }
}
