//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCACAO_ANOTACAO
    {
        public int LOAN_CD_ID { get; set; }
        public int LOCA_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> LOAN_DT_ANOTACAO { get; set; }
        public string LOAN_TX_ANOTACAO { get; set; }
        public int LOAN_IN_ATIVO { get; set; }
    
        public virtual LOCACAO LOCACAO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
