//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCACAO_ANEXO
    {
        public int LOAX_CD_ID { get; set; }
        public int LOCA_CD_ID { get; set; }
        public Nullable<System.DateTime> LOAX_DT_ANEXO { get; set; }
        public string LOAX_NM_TITULO { get; set; }
        public Nullable<int> LOAX_IN_TIPO { get; set; }
        public string LOAX_AQ_ARQUIVO { get; set; }
        public int LOAX_IN_ATIVO { get; set; }
    
        public virtual LOCACAO LOCACAO { get; set; }
    }
}
