//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOG()
        {
            this.PRODUTO_LOG = new HashSet<PRODUTO_LOG>();
            this.SERVICOS_LOG = new HashSet<SERVICOS_LOG>();
        }
    
        public int LOG_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> LOG_DT_DATA { get; set; }
        public string LOG_NM_OPERACAO { get; set; }
        public string LOG_TX_REGISTRO { get; set; }
        public string LOG_TX_REGISTRO_ANTES { get; set; }
        public int LOG_IN_ATIVO { get; set; }
        public Nullable<int> LOG_IN_SISTEMA { get; set; }
        public Nullable<System.DateTime> LOG_DT_DUMMY { get; set; }
        public string LOG_UL_ULID { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_LOG> PRODUTO_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICOS_LOG> SERVICOS_LOG { get; set; }
    }
}
