//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_EXCECAO
    {
        public int LOG_CD_ID { get; set; }
        public Nullable<System.DateTime> LOG_DT_OCORRENCIA { get; set; }
        public string LOG_MODULO { get; set; }
        public string LOG_USUARIO_LOGADO { get; set; }
        public string LOG_ACAO { get; set; }
        public string LOG_EXCECAO1 { get; set; }
    }
}
