//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICOS()
        {
            this.MEDICOS_ENVIO = new HashSet<MEDICOS_ENVIO>();
        }
    
        public int MEDC_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string MEDC_NM_MEDICO { get; set; }
        public string MEDC_NR_CRM { get; set; }
        public Nullable<int> ESPE_CD_ID { get; set; }
        public string MEDC_EM_EMAIL { get; set; }
        public string MEDC_NR_CELULAR { get; set; }
        public string MEDC_NR_TELEFONE { get; set; }
        public string MEDC_GU_IDENTIFICADOR { get; set; }
        public int MEDC_IN_ATIVO { get; set; }
        public string MEDC_NM_ENDERECO { get; set; }
        public string MEDC_NR_NUMERO { get; set; }
        public string MEDC_NM_COMPLEMENTO { get; set; }
        public string MEDC_NM_BAIRRO { get; set; }
        public string MEDC_NM_CIDADE { get; set; }
        public string MEDC_NR_CEP { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
    
        public virtual ESPECIALIDADE ESPECIALIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICOS_ENVIO> MEDICOS_ENVIO { get; set; }
        public virtual UF UF { get; set; }
    }
}
