//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO_ENVIO_INFORMACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICO_ENVIO_INFORMACAO()
        {
            this.MEDICO_ENVIO_INFORMACAO_ANEXO = new HashSet<MEDICO_ENVIO_INFORMACAO_ANEXO>();
            this.MEDICO_ENVIO_INFORMACAO_ANOTACAO = new HashSet<MEDICO_ENVIO_INFORMACAO_ANOTACAO>();
        }
    
        public int MEEN_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> MEEN_DT_ENVIO { get; set; }
        public string MEEN_GU_GUID { get; set; }
        public string MEEN_NM_MEDICO { get; set; }
        public string MEEN_EM_MAIL { get; set; }
        public string MEEN_NR_TELEFONE { get; set; }
        public string MEEN_NR_CELULAR { get; set; }
        public string MEEN_NR_CRM { get; set; }
        public Nullable<int> ESPE_CD_ID { get; set; }
        public string MEEN_TX_MENSAGEM { get; set; }
        public Nullable<int> MEEN_IN_ATIVO { get; set; }
    
        public virtual ESPECIALIDADE ESPECIALIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICO_ENVIO_INFORMACAO_ANEXO> MEDICO_ENVIO_INFORMACAO_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICO_ENVIO_INFORMACAO_ANOTACAO> MEDICO_ENVIO_INFORMACAO_ANOTACAO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
