//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICOS_ENVIO_ANOTACAO
    {
        public int MEAT_CD_ID { get; set; }
        public int MEEV_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> MEAT_DT_ANOTACAO { get; set; }
        public string MEAT_TX_ANOTACAO { get; set; }
        public int MEAT_IN_ATIVO { get; set; }
    
        public virtual MEDICOS_ENVIO MEDICOS_ENVIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
