//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAGEM_FABRICANTE_LIDO
    {
        public int AVLI_CD_ID { get; set; }
        public int MEFA_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> AVLI_DT_CIENCIA { get; set; }
    
        public virtual MENSAGEM_FABRICANTE MENSAGEM_FABRICANTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
