//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAGENS_ENVIADAS_SISTEMA
    {
        public int MEEN_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> EMPR_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<int> CLIE_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public Nullable<int> CRM1_CD_ID { get; set; }
        public Nullable<int> CRCO_CD_ID { get; set; }
        public Nullable<int> PACI_CD_ID { get; set; }
        public Nullable<int> FORN_CD_ID { get; set; }
        public Nullable<int> MEEN_IN_USUARIO { get; set; }
        public Nullable<int> MEEN_IN_ASSINANTE { get; set; }
        public int MEEN_IN_TIPO { get; set; }
        public Nullable<System.DateTime> MEEN_DT_DATA_ENVIO { get; set; }
        public string MEEN_EM_EMAIL_DESTINO { get; set; }
        public string MEEN__CELULAR_DESTINO { get; set; }
        public string MEEN_NM_ORIGEM { get; set; }
        public string MEEN_NM_TITULO { get; set; }
        public string MEEN_TX_CORPO { get; set; }
        public string MEEN_TX_CORPO_COMPLETO { get; set; }
        public Nullable<int> MEEN_IN_ESCOPO { get; set; }
        public Nullable<int> MEEN_IN_ANEXOS { get; set; }
        public Nullable<int> MEEN_IN_ENTREGUE { get; set; }
        public string MEEN_LK_LINK { get; set; }
        public string MEEN_TX_RETORNO { get; set; }
        public int MEEN_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> MEEN_DT_DUMMY { get; set; }
        public string MEEN_SG_STATUS { get; set; }
        public string MEEN_GU_ID_MENSAGEM { get; set; }
        public Nullable<int> MEEN_IN_SISTEMA { get; set; }
        public Nullable<int> COMP_CD_ID { get; set; }
        public Nullable<int> COCO_CD_ID { get; set; }
        public string MEEN_ID_IDENTIFICADOR { get; set; }
        public string MEEN_NR_CELULAR_DESTINO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual ASSINANTE ASSINANTE1 { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual COMPRA COMPRA { get; set; }
        public virtual COMPRA_CONTATO COMPRA_CONTATO { get; set; }
        public virtual CRM CRM { get; set; }
        public virtual CRM_CONTATO CRM_CONTATO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
