//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEM_SERVICO_PRODUTO
    {
        public int OSPR_CD_ID { get; set; }
        public int ORSE_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public Nullable<int> OSPR_IN_QUANTIDADE { get; set; }
        public Nullable<decimal> OSPR_VL_PRECO_NOVO { get; set; }
        public Nullable<int> OSPR_IN_ATIVO { get; set; }
        public string OSPR_DS_OBSERVACAO { get; set; }
        public Nullable<decimal> OSPR_VL_PRECO_PROMO { get; set; }
    
        public virtual ORDEM_SERVICO ORDEM_SERVICO { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
