//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEM_SERVICO_SERVICO
    {
        public int OSSE_CD_ID { get; set; }
        public int ORSE_CD_ID { get; set; }
        public Nullable<int> SERV_CD_ID { get; set; }
        public Nullable<int> OSSE_IN_QUANTIDADE { get; set; }
        public Nullable<decimal> OSSE_VL_PRECO_NOVO { get; set; }
        public string OSSE_DS_OBSERVACOES { get; set; }
        public Nullable<int> OSSE_IN_ATIVO { get; set; }
        public Nullable<decimal> OSSE_VL_PRECO_PROMO { get; set; }
    
        public virtual ORDEM_SERVICO ORDEM_SERVICO { get; set; }
        public virtual SERVICO SERVICO { get; set; }
    }
}
