//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_EXAME_FISICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE_EXAME_FISICOS()
        {
            this.PACIENTE_DADOS_EXAME_FISICO = new HashSet<PACIENTE_DADOS_EXAME_FISICO>();
        }
    
        public int PAEF_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public int PACI_CD_ID { get; set; }
        public Nullable<int> PACO_CD_ID { get; set; }
        public Nullable<System.DateTime> PAEF_DT_DATA { get; set; }
        public Nullable<int> PAEF_NR_PA_ALTA { get; set; }
        public Nullable<int> PAEF_NR_PA_BAIXA { get; set; }
        public Nullable<decimal> PAEF_NR_PESO { get; set; }
        public Nullable<decimal> PAEF_NR_ALTURA { get; set; }
        public Nullable<decimal> PAEF_VL_IMC { get; set; }
        public Nullable<int> PAEF_IN_ATIVO { get; set; }
        public Nullable<int> PAEF_NR_FREQUENCIA_CARDIACA { get; set; }
        public Nullable<decimal> PAEF_NR_TEMPERATURA { get; set; }
        public Nullable<int> PAEF_IN_DIABETE { get; set; }
        public Nullable<int> PAEF_IN_HIPERTENSAO { get; set; }
        public Nullable<int> PAEF_IN_TABAGISMO { get; set; }
        public Nullable<int> PAEF_IN_VARIZES { get; set; }
        public Nullable<int> PAEF_IN_EPILEPSIA { get; set; }
        public Nullable<int> PAEF_IN_GESTANTE { get; set; }
        public Nullable<int> PAEF_IN_HIPOTENSAO { get; set; }
        public Nullable<int> PAEF_IN_CIRURGIAS { get; set; }
        public string PAEF_TX_CIRURGIAS { get; set; }
        public Nullable<int> PAEF_IN_EXERCICIO_FISICO { get; set; }
        public Nullable<int> PAEF_IN_EXERCICIO_FISICO_FREQUENCIA { get; set; }
        public Nullable<int> PAEF_IN_ALCOOLISMO { get; set; }
        public Nullable<int> PAEF_IN_ALCOOLISMO_FREQUENCIA { get; set; }
        public Nullable<int> PAEF_IN_ANTE_ALERGICO { get; set; }
        public Nullable<int> PAEF_IN_ANTE_ONCOLOGICO { get; set; }
        public Nullable<int> PAEF_IN_ANTICONCEPCIONAL { get; set; }
        public string PAEF_DS_ANTICONCEPCIONAL { get; set; }
        public Nullable<int> PAEF_IN_MARCAPASSO { get; set; }
        public string PAEF_DS_EXAME_FISICO { get; set; }
        public Nullable<int> PAEF_NR_MES_GESTANTE { get; set; }
        public string PAEF_DS_EXERCICIO_FISICO { get; set; }
        public string PAEF_DS_ALCOOLISMO { get; set; }
        public string PAEF_DS_ALERGICO { get; set; }
        public string PAEF_DS_ONCOLOGICO { get; set; }
        public string PAEF_DS_TABAGISMO { get; set; }
        public string PAEF_DS_MARCAPASSO { get; set; }
        public Nullable<int> PAEF_IN_PREENCHIDO { get; set; }
        public Nullable<System.DateTime> PAEF_DT_COPIA { get; set; }
        public string PAEF_TX_RESULTADOS { get; set; }
        public Nullable<System.DateTime> PAEF_DT_ORIGINAL { get; set; }
        public string PAEF_TX_RESULTADOS_OLD { get; set; }
        public string PAEF_DS_EXERCICIO_FISICO_LONG { get; set; }
        public string PAEF_DS_ALCOOLISMO_LONG { get; set; }
        public string PAEF_DS_ALERGICO_LONG { get; set; }
        public string PAEF_DS_ONCOLOGICO_LONG { get; set; }
        public string PAEF_DS_TABAGISMO_LONG { get; set; }
        public string PAEF_DS_MARCAPASSO_LONG { get; set; }
        public string PAEF_DS_FICHA_AVALIACAO { get; set; }
        public string PAEF_NM_TIPO_SANGUE { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual PACIENTE_CONSULTA PACIENTE_CONSULTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_DADOS_EXAME_FISICO> PACIENTE_DADOS_EXAME_FISICO { get; set; }
    }
}
