//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_VACINA
    {
        public int PAVI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int PACI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> VACI_CD_ID { get; set; }
        public Nullable<System.DateTime> PAVI_DT_DATA { get; set; }
        public Nullable<int> PAVI_IN_ATIVO { get; set; }
        public string PAVI_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> PAVI_DT_PROXIMA { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual VACINA VACINA { get; set; }
    }
}
