//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_DADOS_EXAME_FISICO
    {
        public int PDEF_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int PAEF_CD_ID { get; set; }
        public int PACI_CD_ID { get; set; }
        public Nullable<decimal> PDEF_IN_PESO { get; set; }
        public Nullable<decimal> PDEF_IN_ALTURA { get; set; }
        public Nullable<int> PDEF_IN_PRESSAO_ALTA { get; set; }
        public Nullable<int> PDEF_IN_PRESSAO_BAIXA { get; set; }
        public Nullable<int> PDEF_IN_FREQUENCIA { get; set; }
        public Nullable<decimal> PDEF_IN_TEMPERATURA { get; set; }
        public Nullable<System.DateTime> PDEF_DT_DATA { get; set; }
        public Nullable<int> PDEF_IN_HIPOTENSAO { get; set; }
        public Nullable<int> PDEF_IN_HIPERTENSAO { get; set; }
        public Nullable<int> PDEF_IN_DIABETES { get; set; }
        public Nullable<int> PDEF_IN_VARIZES { get; set; }
        public Nullable<int> PDEF_IN_EPILEPSIA { get; set; }
        public Nullable<int> PDEF_IN_TABAGISMO { get; set; }
        public Nullable<int> PDEF_IN_ALCOOLISMO { get; set; }
        public Nullable<int> PDEF_IN_EXERCICIO_FISICO { get; set; }
        public Nullable<int> PDEF_IN_ANTICONCEPCIONAL { get; set; }
        public Nullable<int> PDEF_IN_MARCAPASSO { get; set; }
        public Nullable<int> PDEF_IN_CIRURGIAS { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual PACIENTE_EXAME_FISICOS PACIENTE_EXAME_FISICOS { get; set; }
    }
}
