//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_ANAMNESE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE_ANAMNESE()
        {
            this.PACIENTE_ANAMNESE_ANOTACAO = new HashSet<PACIENTE_ANAMNESE_ANOTACAO>();
        }
    
        public int PAAM_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public int PACI_CD_ID { get; set; }
        public Nullable<int> PACO_CD_ID { get; set; }
        public System.DateTime PAAM_DT_DATA { get; set; }
        public string PAAM_DS_MOTIVO_CONSULTA { get; set; }
        public string PAAM_DS_HISTORIA_FAMILIAR { get; set; }
        public string PAAM_DS_HISTORIA_SOCIAL { get; set; }
        public string PAAN_NM_AVALIACAO_CARDIOLOGICA { get; set; }
        public string PAAN_NM_RESPIRATORIO { get; set; }
        public string PAAN_NM_ABDOMEM { get; set; }
        public string PAAN_NM_MEMBROS_INFERIORES { get; set; }
        public string PAAM_DS_QUEIXA_PRINCIPAL { get; set; }
        public string PAAM_DS_HISTORIA_DOENCA_ATUAL { get; set; }
        public string PAAM_DS_HISTORIA_PATOLOGICA_PROGRESSIVA { get; set; }
        public string PAAM_DS_DIAGNOSTICO_1 { get; set; }
        public string PAAM_DS_DIAGNOSTICO_2 { get; set; }
        public string PAAM_DS_CONDUTA { get; set; }
        public string PAAM_TX_OBSERVACOES { get; set; }
        public int PAAM_IN_ATIVO { get; set; }
        public Nullable<int> PAAM_IN_PREENCHIDA { get; set; }
        public Nullable<System.DateTime> PAAM_DT_COPIA { get; set; }
        public Nullable<int> PAAM_IN_FLAG_MOTIVO_CONSULTA { get; set; }
        public Nullable<int> PAAM_IN_FLAG__HISTORIA_FAMILIAR { get; set; }
        public Nullable<int> PAAM_IN_FLAG_HISTORIA_SOCIAL { get; set; }
        public Nullable<int> PAAM_IN_FLAG_AVALIACAO_CARDIOLOGICA { get; set; }
        public Nullable<int> PAAM_IN_FLAG_RESPIRATORIO { get; set; }
        public Nullable<int> PAAM_IN_FLAG_ABDOMEM { get; set; }
        public Nullable<int> PAAM_IN_FLAG_MEMBROS_INFERIORES { get; set; }
        public Nullable<int> PAAM_IN_FLAG_QUEIXA_PRINCIPAL { get; set; }
        public Nullable<int> PAAM_IN_FLAG_HISTORIA_DOENCA_ATUAL { get; set; }
        public Nullable<int> PAAM_IN_FLAG_HISTORIA_PROGRESSIVA { get; set; }
        public Nullable<int> PAAM_IN_FLAG_DIAGNOSTICO_1 { get; set; }
        public Nullable<int> PAAM_IN_FLAG_DIAGNOSTICO_2 { get; set; }
        public string PAAM_NM_CAMPO_1 { get; set; }
        public string PAAM_DS_CAMPO_1 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_1 { get; set; }
        public string PAAM_NM_CAMPO_2 { get; set; }
        public string PAAM_DS_CAMPO_2 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_2 { get; set; }
        public string PAAM_NM_CAMPO_3 { get; set; }
        public string PAAM_DS_CAMPO_3 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_3 { get; set; }
        public Nullable<int> PAAM_IN_FLAG_MEDICAMENTO { get; set; }
        public string PAAM_NM_MEDICAMENTO { get; set; }
        public string PAAM_NM_CAMPO_4 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_4 { get; set; }
        public string PAAM_DS_CAMPO_4 { get; set; }
        public string PAAM_NM_CAMPO_5 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_5 { get; set; }
        public string PAAM_DS_CAMPO_5 { get; set; }
        public string PAAM_TX_COMPLETA { get; set; }
        public Nullable<System.DateTime> PAAM_DT_ORIGINAL { get; set; }
        public Nullable<int> PAAM_IN_ALTERADA { get; set; }
        public string PAAM_NM_CAMPO_6 { get; set; }
        public string PAAM_NM_CAMPO_7 { get; set; }
        public string PAAM_NM_CAMPO_8 { get; set; }
        public string PAAM_NM_CAMPO_9 { get; set; }
        public string PAAM_NM_CAMPO_10 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_6 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_7 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_8 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_9 { get; set; }
        public Nullable<int> PAAM_IN_CAMPO_10 { get; set; }
        public string PAAM_DS_CAMPO_6 { get; set; }
        public string PAAM_DS_CAMPO_7 { get; set; }
        public string PAAM_DS_CAMPO_8 { get; set; }
        public string PAAM_DS_CAMPO_9 { get; set; }
        public string PAAM_DS_CAMPO_10 { get; set; }
        public string PAAN_NM_AVALIACAO_CARDIOLOGICA_LONG { get; set; }
        public string PAAN_NM_RESPIRATORIO_LONG { get; set; }
        public string PAAM_DS_DIAGNOSTICO_1_LONG { get; set; }
        public string PAAM_DS_DIAGNOSTICO_2_LONG { get; set; }
        public string PAAM_DS_SONO_PRINCIPAL_QUEIXA { get; set; }
        public string PAAM_DS_SONO_SINTOMAS { get; set; }
        public Nullable<int> PAAM_DS_SONO_HORARIO_REGULAR { get; set; }
        public Nullable<int> PAAM_DS_SONO_LATENCIA { get; set; }
        public string PAAM_DS_SONO_DURACAO { get; set; }
        public Nullable<int> PAAM_DS_SONO_ROTINA_FDS { get; set; }
        public Nullable<int> PAAM_DS_SONO_COCHILOS { get; set; }
        public Nullable<int> PAAM_DS_SONO_TVCAMA { get; set; }
        public Nullable<int> PAAM_DS_SONO_DEITADO_SONO { get; set; }
        public Nullable<int> PAAM_DS_SONO_CELULAR_CAMA { get; set; }
        public Nullable<int> PAAM_DS_SONO_LECAMA { get; set; }
        public Nullable<int> PAAM_DS_SONO_FUMA_NOITE { get; set; }
        public string PAAM_DS_SONO_ULTIMO_ALCOOL { get; set; }
        public Nullable<int> PAAM_DS_SONO_REFEICAO_PESADA { get; set; }
        public Nullable<int> PAAM_DS_SONO_TODAS_REFEICOES { get; set; }
        public Nullable<int> PAAM_DS_SONO_CAFE { get; set; }
        public Nullable<int> PAAM_DS_SONO_ALMOCO { get; set; }
        public Nullable<int> PAAM_DS_SONO_LANCHE { get; set; }
        public Nullable<int> PAAM_DS_SONO_JANTAR { get; set; }
        public Nullable<int> PAAM_DS_SONO_EXERCICIO { get; set; }
        public string PAAM_DS_SONO_EXERCICIO_FREQ { get; set; }
        public string PAAM_DS_SONO_QUANTAS_DESPERTA { get; set; }
        public string PAAM_DS_SONO_MOTIVOS_DESPERTA { get; set; }
        public string PAAM_DS_SONO_TEMPO_PEGAR_SONO { get; set; }
        public Nullable<int> PAAM_DS_SONO_DEITADO_PERDE_SONO { get; set; }
        public string PAAM_DS_SONO_URINA_NOITE { get; set; }
        public Nullable<int> PAAM_DS_SONO_ENGASGOS { get; set; }
        public Nullable<int> PAAM_DS_SONO_TOSSE { get; set; }
        public Nullable<int> PAAM_DS_SONO_REFLUXO { get; set; }
        public Nullable<int> PAAM_DS_SONO_SUDORESE { get; set; }
        public string PAAM_DS_SONO_POSICAO_DORMIR { get; set; }
        public Nullable<int> PAAM_DS_SONO_RANGE { get; set; }
        public Nullable<int> PAAM_DS_SONO_RIGIDEZ_FACE { get; set; }
        public Nullable<int> PAAM_DS_SONO_APNEIA { get; set; }
        public Nullable<int> PAAM_DS_SONO_RONCO { get; set; }
        public Nullable<int> PAAM_DS_SONO_AGRESSIVO { get; set; }
        public Nullable<int> PAAM_DS_SONO_FALA { get; set; }
        public Nullable<int> PAAM_DS_SONO_PESADELO { get; set; }
        public Nullable<int> PAAM_DS_SONO_SONANBULISMO { get; set; }
        public Nullable<int> PAAM_DS_SONO_ENCENACAO { get; set; }
        public Nullable<int> PAAM_DS_SONO_MOVE_MEMBRO { get; set; }
        public Nullable<int> PAAM_DS_SONO_CAIBRAS { get; set; }
        public Nullable<int> PAAM_DS_SONO_ACONCHEGANTE { get; set; }
        public Nullable<int> PAAM_DS_SONO_BARULHO { get; set; }
        public Nullable<int> PAAM_DS_SONO_TEMPERATURA { get; set; }
        public Nullable<int> PAAM_DS_SONO_PESSOAS { get; set; }
        public Nullable<int> PAAM_DS_SONO_ANIMAIS { get; set; }
        public string PAAM_DS_SONO_ATIVIDADES { get; set; }
        public Nullable<int> PAAM_DS_SONO_FINANCAS { get; set; }
        public Nullable<int> PAAM_DS_SONO_ACESSO_SAUDE { get; set; }
        public Nullable<int> PAAM_DS_SONO_REPARADOR { get; set; }
        public Nullable<int> PAAM_DS_SONO_SONOLENCIA { get; set; }
        public Nullable<int> PAAM_DS_SONO_BOCA_SECA { get; set; }
        public Nullable<int> PAAM_DS_SONO_DOR_CABECA { get; set; }
        public Nullable<int> PAAM_DS_SONO_CONGESTAO { get; set; }
        public Nullable<int> PAAM_DS_SONO_AZIA { get; set; }
        public Nullable<int> PAAM_DS_SONO_SONOLENCIA_DIURNA { get; set; }
        public Nullable<int> PAAM_DS_SONO_CANSACO { get; set; }
        public Nullable<int> PAAM_DS_SONO_DEFICIT { get; set; }
        public Nullable<int> PAAM_DS_SONO_FADIGA { get; set; }
        public Nullable<int> PAAM_DS_SONO_IRRITA { get; set; }
        public Nullable<int> PAAM_DS_SONO_DOR { get; set; }
        public Nullable<int> PAAM_DS_SONO_TIPO_RESPIRACAO { get; set; }
        public Nullable<int> PAAM_DS_SONO_DISFUNCAO { get; set; }
        public Nullable<int> PAAM_DS_SONO_PONDERAL { get; set; }
        public string PAAM_DS_SONO_MEDICAMENTOS { get; set; }
        public string PAAM_DS_SONO_COMORBIDADES { get; set; }
        public string PAAM_DS_SONO_CIRURGIAS { get; set; }
        public Nullable<int> PAAM_DS_SONO_SENSACAO_PERNA { get; set; }
        public Nullable<int> PAAM_DS_SONO_TURNO { get; set; }
        public string PAAM_DS_SONO_MALLAMPATI { get; set; }
        public string PAAM_DS_SONO_OVERLAP { get; set; }
        public string PAAM_DS_SONO_PATOLOGIAS { get; set; }
        public string PAAM_TX_TEXTO_LIVRE { get; set; }
        public string PAAM_DS_SONO_PRINCIPAL_QUEIXA_OLD { get; set; }
        public string PAAM_DS_SONO_SINTOMAS_OLD { get; set; }
        public string PAAM_DS_SONO_DURACAO_OLD { get; set; }
        public string PAAM_DS_SONO_ULTIMO_ALCOOL_OLD { get; set; }
        public string PAAM_DS_SONO_EXERCICIO_FREQ_OLD { get; set; }
        public string PAAM_DS_SONO_QUANTAS_DESPERTA_OLD { get; set; }
        public string PAAM_DS_SONO_MOTIVOS_DESPERTA_OLD { get; set; }
        public string PAAM_DS_SONO_TEMPO_PEGAR_SONO_OLD { get; set; }
        public string PAAM_DS_SONO_URINA_NOITE_OLD { get; set; }
        public string PAAM_DS_SONO_POSICAO_DORMIR_OLD { get; set; }
        public string PAAM_DS_SONO_ATIVIDADES_OLD { get; set; }
        public string PAAM_DS_SONO_MEDICAMENTOS_OLD { get; set; }
        public string PAAM_DS_SONO_COMORBIDADES_OLD { get; set; }
        public string PAAM_DS_SONO_CIRURGIAS_OLD { get; set; }
        public string PAAM_DS_SONO_MALLAMPATI_OLD { get; set; }
        public string PAAM_DS_SONO_OVERLAP_OLD { get; set; }
        public string PAAM_DS_SONO_PATOLOGIAS_OLD { get; set; }
        public string PAAM_TX_TEXTO_LIVRE_OLD { get; set; }
        public Nullable<int> PAAM_DS_SONO_DEFICIT_MEMORIA { get; set; }
        public string PAAM_DS_SONO_EXERCICIO_HORARIO { get; set; }
        public string PAAM_DS_SONO_HORARIO_REGULAR_NOVO { get; set; }
        public string PAAM_DS_SONO_HORARIO_REGULAR_NOVO_OLD { get; set; }
        public string PAAM_DS_SONO_LATENCIA_NOVO { get; set; }
        public string PAAM_DS_SONO_LATENCIA_NOVO_OLD { get; set; }
        public Nullable<int> PAAM_DS_SONO_DEFICIT_CONCENTRA { get; set; }
        public Nullable<int> PAAM_DS_SONO_DEFICIT_MEMO { get; set; }
        public Nullable<int> PAAM_DS_SONO_RIGIDEZ_FACE_OUTROS { get; set; }
        public string PAAM_DS_SONO_POLISONO { get; set; }
        public string PAAM_DS_SONO_POLISONO_OLD { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ANAMNESE_ANOTACAO> PACIENTE_ANAMNESE_ANOTACAO { get; set; }
        public virtual PACIENTE_CONSULTA PACIENTE_CONSULTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
