//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.ACESSO_METODO = new HashSet<ACESSO_METODO>();
            this.AGENDA = new HashSet<AGENDA>();
            this.AVISO_LEMBRETE = new HashSet<AVISO_LEMBRETE>();
            this.CONSULTA_RECEBIMENTO = new HashSet<CONSULTA_RECEBIMENTO>();
            this.GRUPO_PACIENTE = new HashSet<GRUPO_PACIENTE>();
            this.MENSAGENS = new HashSet<MENSAGENS>();
            this.MENSAGENS_DESTINOS = new HashSet<MENSAGENS_DESTINOS>();
            this.MENSAGENS_ENVIADAS_SISTEMA = new HashSet<MENSAGENS_ENVIADAS_SISTEMA>();
            this.PACIENTE_ANAMNESE = new HashSet<PACIENTE_ANAMNESE>();
            this.PACIENTE_ANEXO = new HashSet<PACIENTE_ANEXO>();
            this.PACIENTE_ANOTACAO = new HashSet<PACIENTE_ANOTACAO>();
            this.PACIENTE_ANOTACAO1 = new HashSet<PACIENTE_ANOTACAO>();
            this.PACIENTE_ATESTADO = new HashSet<PACIENTE_ATESTADO>();
            this.PACIENTE_CONSULTA = new HashSet<PACIENTE_CONSULTA>();
            this.PACIENTE_CONTATO = new HashSet<PACIENTE_CONTATO>();
            this.PACIENTE_EXAME_ANEXO = new HashSet<PACIENTE_EXAME_ANEXO>();
            this.PACIENTE_EXAME_ANOTACAO = new HashSet<PACIENTE_EXAME_ANOTACAO>();
            this.PACIENTE_EXAME_FISICOS = new HashSet<PACIENTE_EXAME_FISICOS>();
            this.PACIENTE_EXAMES = new HashSet<PACIENTE_EXAMES>();
            this.PACIENTE_FICHA = new HashSet<PACIENTE_FICHA>();
            this.PACIENTE_HISTORICO = new HashSet<PACIENTE_HISTORICO>();
            this.PACIENTE_LOGIN = new HashSet<PACIENTE_LOGIN>();
            this.PACIENTE_PRESCRICAO_ITEM = new HashSet<PACIENTE_PRESCRICAO_ITEM>();
            this.PACIENTE_PRESCRICAO = new HashSet<PACIENTE_PRESCRICAO>();
            this.PACIENTE_SOLICITACAO = new HashSet<PACIENTE_SOLICITACAO>();
            this.RECURSIVIDADE_DESTINO = new HashSet<RECURSIVIDADE_DESTINO>();
            this.RESULTADO_ROBOT = new HashSet<RESULTADO_ROBOT>();
            this.PACIENTE_DADOS_EXAME_FISICO = new HashSet<PACIENTE_DADOS_EXAME_FISICO>();
            this.MEDICOS_ENVIO = new HashSet<MEDICOS_ENVIO>();
            this.QUESTIONARIO_BERLIM = new HashSet<QUESTIONARIO_BERLIM>();
            this.QUESTIONARIO_EPWORTH = new HashSet<QUESTIONARIO_EPWORTH>();
            this.QUESTIONARIO_STOPBANG = new HashSet<QUESTIONARIO_STOPBANG>();
            this.LOCACAO = new HashSet<LOCACAO>();
            this.RESPOSTA_CONSULTA = new HashSet<RESPOSTA_CONSULTA>();
            this.AREA_PACIENTE = new HashSet<AREA_PACIENTE>();
            this.NOTICIA_COMENTARIO = new HashSet<NOTICIA_COMENTARIO>();
            this.PACIENTE_VACINA = new HashSet<PACIENTE_VACINA>();
        }
    
        public int PACI__CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int TIPA_CD_ID { get; set; }
        public string PACI_NM_NOME { get; set; }
        public string PACI_NM_SOCIAL { get; set; }
        public Nullable<int> SEXO_CD_ID { get; set; }
        public Nullable<int> COR1_CD_ID { get; set; }
        public Nullable<int> ESCI_CD_ID { get; set; }
        public Nullable<int> CONV_CD_ID { get; set; }
        public string PACI_NM_PAI { get; set; }
        public string PACI_NM_MAE { get; set; }
        public string PACI_NR_CEP { get; set; }
        public string PACI_NM_ENDERECO { get; set; }
        public string PACI_NR_NUMERO { get; set; }
        public string PACI_NR_COMPLEMENTO { get; set; }
        public string PACI_NM_BAIRRO { get; set; }
        public string PACI_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string PACI_NM_PROFISSAO { get; set; }
        public Nullable<System.DateTime> PACI_DT_NASCIMENTO { get; set; }
        public string PACI_NM_NATURALIDADE { get; set; }
        public string PACI_NM_NACIONALIDADE { get; set; }
        public string PACI_NR_CPF { get; set; }
        public string PACI_NR_RG { get; set; }
        public string PACI_NR_TELEFONE { get; set; }
        public string PACI_NR_CELULAR { get; set; }
        public string PACI_NM_EMAIL { get; set; }
        public Nullable<int> PACI_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> PACI_DT_CADASTRO { get; set; }
        public string PACI_AQ_FOTO { get; set; }
        public string PACI_NR_MATRICULA { get; set; }
        public Nullable<int> GRAU_CD_ID { get; set; }
        public Nullable<System.DateTime> PACI_DT_PREVISAO_RETORNO { get; set; }
        public string PACI_NM_INDICACAO { get; set; }
        public string PACI_TX_OBSERVACOES { get; set; }
        public Nullable<int> NACI_CD_ID { get; set; }
        public Nullable<int> MUNI_CD_ID { get; set; }
        public Nullable<int> MUNI_SG_UF { get; set; }
        public string PACI_GU_GUID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> PACI_DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> PACI_DT_CONSULTA { get; set; }
        public string PACI_SG_NATURALIDADE_UF { get; set; }
        public Nullable<int> PACI_NR_IDADE { get; set; }
        public Nullable<System.DateTime> PACI_DT_ULTIMO_ACESSO { get; set; }
        public Nullable<System.DateTime> PACI_DT_ACESSO { get; set; }
        public Nullable<int> PACI_IN_COMPLETADO { get; set; }
        public Nullable<int> PACI_IN_MENOR { get; set; }
        public string PACI_NM_RESPONSAVEL { get; set; }
        public Nullable<int> PACI_IN_FICHAS { get; set; }
        public Nullable<int> PACI_IN_PADRAO_ANAMNESE { get; set; }
        public Nullable<int> PACI_IN_PADRAO_CONTINUA { get; set; }
        public Nullable<int> VACO_CD_ID { get; set; }
        public Nullable<System.DateTime> PACI_DT_PRECO { get; set; }
        public string PACI_NM_LOGIN { get; set; }
        public string PACI_NM_SENHA { get; set; }
        public Nullable<int> PACI_IN_HUMANO { get; set; }
        public string PACI_NM_NOVA_SENHA { get; set; }
        public string PACI_NM_SENHA_CONFIRMA { get; set; }
        public Nullable<int> PACI_IN_MENSAGEM_ATRASO { get; set; }
        public Nullable<int> PACI_IN_NUMERO_ENVIO { get; set; }
        public Nullable<System.DateTime> PACI_DT_ULTIMO_ENVIO { get; set; }
        public Nullable<int> PACI_IN_FIM_ENVIO { get; set; }
        public Nullable<int> RACA_CD_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACESSO_METODO> ACESSO_METODO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENDA> AGENDA { get; set; }
        public virtual ASSINANTE ASSINANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVISO_LEMBRETE> AVISO_LEMBRETE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTA_RECEBIMENTO> CONSULTA_RECEBIMENTO { get; set; }
        public virtual CONVENIO CONVENIO { get; set; }
        public virtual COR COR { get; set; }
        public virtual ESTADO_CIVIL ESTADO_CIVIL { get; set; }
        public virtual GRAU_INSTRUCAO GRAU_INSTRUCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO_PACIENTE> GRUPO_PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGENS> MENSAGENS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGENS_DESTINOS> MENSAGENS_DESTINOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGENS_ENVIADAS_SISTEMA> MENSAGENS_ENVIADAS_SISTEMA { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual NACIONALIDADE NACIONALIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ANAMNESE> PACIENTE_ANAMNESE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ANEXO> PACIENTE_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ANOTACAO> PACIENTE_ANOTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ANOTACAO> PACIENTE_ANOTACAO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ATESTADO> PACIENTE_ATESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_CONSULTA> PACIENTE_CONSULTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_CONTATO> PACIENTE_CONTATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_EXAME_ANEXO> PACIENTE_EXAME_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_EXAME_ANOTACAO> PACIENTE_EXAME_ANOTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_EXAME_FISICOS> PACIENTE_EXAME_FISICOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_EXAMES> PACIENTE_EXAMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_FICHA> PACIENTE_FICHA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_HISTORICO> PACIENTE_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_LOGIN> PACIENTE_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_PRESCRICAO_ITEM> PACIENTE_PRESCRICAO_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_PRESCRICAO> PACIENTE_PRESCRICAO { get; set; }
        public virtual SEXO SEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_SOLICITACAO> PACIENTE_SOLICITACAO { get; set; }
        public virtual TIPO_PACIENTE TIPO_PACIENTE { get; set; }
        public virtual UF UF { get; set; }
        public virtual UF UF1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual VALOR_CONSULTA VALOR_CONSULTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECURSIVIDADE_DESTINO> RECURSIVIDADE_DESTINO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADO_ROBOT> RESULTADO_ROBOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_DADOS_EXAME_FISICO> PACIENTE_DADOS_EXAME_FISICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICOS_ENVIO> MEDICOS_ENVIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTIONARIO_BERLIM> QUESTIONARIO_BERLIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTIONARIO_EPWORTH> QUESTIONARIO_EPWORTH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTIONARIO_STOPBANG> QUESTIONARIO_STOPBANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCACAO> LOCACAO { get; set; }
        public virtual RACA RACA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPOSTA_CONSULTA> RESPOSTA_CONSULTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AREA_PACIENTE> AREA_PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTICIA_COMENTARIO> NOTICIA_COMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_VACINA> PACIENTE_VACINA { get; set; }
    }
}
