//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_EXAME_ANEXO
    {
        public int PAEO_CD_ID { get; set; }
        public int PACI_CD_ID { get; set; }
        public int PAEX_CD_ID { get; set; }
        public Nullable<System.DateTime> PAEO_DT_ANEXO { get; set; }
        public Nullable<int> PAEO_IN_TIPO { get; set; }
        public string PAEO_NM_TITULO { get; set; }
        public string PAEO_AQ_ARQUIVO { get; set; }
        public Nullable<int> PAEO_IN_ATIVO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual PACIENTE_EXAMES PACIENTE_EXAMES { get; set; }
    }
}
