//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGAMENTO_NOTA_FISCAL
    {
        public int PANF_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int COPA_CD_ID { get; set; }
        public string PANF_NR_NUMERO { get; set; }
        public string PANF_NR_SERIE { get; set; }
        public Nullable<System.DateTime> PANF_DT_EMISSAO { get; set; }
        public string PANF_NM_EMITENTE { get; set; }
        public Nullable<decimal> PANF_VL_VALOR { get; set; }
        public string PANF_XM_CONTEUDO { get; set; }
        public int PANF_IN_ATIVO { get; set; }
        public string PANF_AQ_ARQUIVO { get; set; }
        public string PANF_NM_NOME { get; set; }
    
        public virtual CONSULTA_PAGAMENTO CONSULTA_PAGAMENTO { get; set; }
    }
}
