//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_VENDA_ACOMPANHAMENTO
    {
        public int PVAC_CD_ID { get; set; }
        public int PEVE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public string PVAC_DS_ACOMPANHAMENTO { get; set; }
        public int PVAC_IN_ATIVO { get; set; }
        public System.DateTime PVAC_DT_ACOMPANHAMENTO { get; set; }
    
        public virtual PEDIDO_VENDA PEDIDO_VENDA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
