//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESQUISA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PESQUISA()
        {
            this.MENSAGENS = new HashSet<MENSAGENS>();
            this.PESQUISA_ENVIO = new HashSet<PESQUISA_ENVIO>();
            this.PESQUISA_ANOTACAO = new HashSet<PESQUISA_ANOTACAO>();
            this.PESQUISA_ANEXO = new HashSet<PESQUISA_ANEXO>();
            this.PESQUISA_ITEM = new HashSet<PESQUISA_ITEM>();
            this.PESQUISA_RESPOSTA = new HashSet<PESQUISA_RESPOSTA>();
        }
    
        public int PESQ_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> GRUP_CD_ID { get; set; }
        public Nullable<int> TEEM_CD_ID { get; set; }
        public Nullable<int> CLIE_CD_ID { get; set; }
        public int TIPS_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public string PESQ_NM_CAMPANHA { get; set; }
        public string PESQ_NM_NOME { get; set; }
        public string PESQ_DS_DESCRICAO { get; set; }
        public System.DateTime PESQ_DT_CRIACAO { get; set; }
        public System.DateTime PESQ_DT_VALIDADE { get; set; }
        public string PESQ_LK_LINK { get; set; }
        public string PESQ_TX_CABECALHO { get; set; }
        public string PESQ_TX_CORPO { get; set; }
        public string PESQ_TX_RODAPE { get; set; }
        public byte[] PESQ_TX_OBSERVACAO { get; set; }
        public int PESQ_IN_ATIVO { get; set; }
        public string PESQ_TX_OBSERVACOES { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual GRUPO GRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGENS> MENSAGENS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_ENVIO> PESQUISA_ENVIO { get; set; }
        public virtual TEMPLATE_EMAIL TEMPLATE_EMAIL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_ANOTACAO> PESQUISA_ANOTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_ANEXO> PESQUISA_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_ITEM> PESQUISA_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESQUISA_RESPOSTA> PESQUISA_RESPOSTA { get; set; }
        public virtual TIPO_PESQUISA TIPO_PESQUISA { get; set; }
    }
}
