//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESQUISA_RESPOSTA_ITEM
    {
        public int PERT_CD_ID { get; set; }
        public int PERE_CD_ID { get; set; }
        public int PEIT_CD_ID { get; set; }
        public Nullable<int> PEIO_CD_ID { get; set; }
        public string PERT_NM_RESPOSTA { get; set; }
        public Nullable<int> PERT_IN_OPCAO { get; set; }
    
        public virtual PESQUISA_ITEM PESQUISA_ITEM { get; set; }
        public virtual PESQUISA_ITEM_OPCAO PESQUISA_ITEM_OPCAO { get; set; }
        public virtual PESQUISA_RESPOSTA PESQUISA_RESPOSTA { get; set; }
    }
}
