//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANO_ASSINATURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANO_ASSINATURA()
        {
            this.ASSINANTE_PAGAMENTO = new HashSet<ASSINANTE_PAGAMENTO>();
            this.ASSINANTE_PLANO_ASSINATURA = new HashSet<ASSINANTE_PLANO_ASSINATURA>();
        }
    
        public int PLAS_CD_ID { get; set; }
        public int PLPE_CD_ID { get; set; }
        public int PLAS_IN_ATIVO { get; set; }
        public int PLAS_IN_SISTEMA { get; set; }
        public string PLAS_NM_NOME { get; set; }
        public string PLAS_NM_EXIBE { get; set; }
        public System.DateTime PLAS_DT_CRIACAO { get; set; }
        public string PLAS_DS_DESCRICAO { get; set; }
        public System.DateTime PLAS_DT_VALIDADE { get; set; }
        public decimal PLAS_VL_PRECO { get; set; }
        public decimal PLAS_VL_PROMOCAO { get; set; }
        public int PLAS_IN_MENSAGERIA { get; set; }
        public int PLAS_NR_CLIENTES { get; set; }
        public int PLAS_NR_EMAIL { get; set; }
        public int PLAS_NR_USUARIOS { get; set; }
        public int PLAS_NR_SMS { get; set; }
        public int PLAS_NR_WHATSAPP { get; set; }
        public int PLAS_NR_GRUPO { get; set; }
        public int PLAS_NR_ITEM_GRUPO { get; set; }
        public int PLAS_IN_COMERCIAL { get; set; }
        public int PLAS_NR_PRODUTO { get; set; }
        public int PLAS_NR_SERVICO { get; set; }
        public int PLAS_NR_PROCESSO { get; set; }
        public int PLAS_NR_ACAO { get; set; }
        public int PLAS_NR_FORNECEDOR { get; set; }
        public int PLAS_NR_PROPOSTA { get; set; }
        public int PLAS_IN_OPERACIONAL { get; set; }
        public int PLAS_NR_COMPRA { get; set; }
        public int PLAS_NR_VENDA { get; set; }
        public int PLAS_NR_PATRIMONIO { get; set; }
        public int PLAS_IN_FINANCEIRO { get; set; }
        public int PLAS_NR_CONTAS { get; set; }
        public int PLAS_NR_CP { get; set; }
        public int PLAS_NR_CR { get; set; }
        public Nullable<int> PLAS_IN_CRM { get; set; }
        public Nullable<int> PLAS_IN_PRECIFICACAO { get; set; }
        public Nullable<int> PLAS_NR_PRECIFICACAO { get; set; }
        public Nullable<int> PLAS_IN_ESTOQUE { get; set; }
        public Nullable<int> PLAS_IN_SONO { get; set; }
        public Nullable<int> PLAS_IN_LOCACAO { get; set; }
        public Nullable<int> PLAS_NR_LOCACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSINANTE_PAGAMENTO> ASSINANTE_PAGAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSINANTE_PLANO_ASSINATURA> ASSINANTE_PLANO_ASSINATURA { get; set; }
        public virtual PLANO_PERIODICIDADE PLANO_PERIODICIDADE { get; set; }
    }
}
