//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCEDIMENTO
    {
        public int PROC_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> CASE_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public Nullable<int> NBSE_CD_ID { get; set; }
        public string PROC_NM_NOME { get; set; }
        public string PROC_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> PROC_DT_CADASTRO { get; set; }
        public Nullable<int> PROC_IN_ATIVO { get; set; }
        public Nullable<int> PROC_NR_DURACAO { get; set; }
        public Nullable<int> PROC_IN_LOCAL { get; set; }
        public Nullable<System.DateTime> PROC_DT_ALTERACAO { get; set; }
        public string PROC_AQ_FOTO { get; set; }
        public string PROC_CD_CODIGO { get; set; }
    }
}
