//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_FALHA
    {
        public int PRFA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<int> PRFA_IN_TIPO { get; set; }
        public Nullable<int> PRFA_IN_NUMERO { get; set; }
        public string PRFA_NM_NOME { get; set; }
        public string PRFA_NR_CODIGO { get; set; }
        public Nullable<System.DateTime> PRFA_DT_DATA { get; set; }
        public Nullable<System.DateTime> PRFA_DT_DUMMY { get; set; }
        public string PRFA_DS_MOTIVO { get; set; }
        public Nullable<int> PRFA_IN_SISTEMA { get; set; }
        public string PRFA_NM_INFO { get; set; }
        public string PRFA_NM_INFO_1 { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
