//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO()
        {
            this.ATENDIMENTO = new HashSet<ATENDIMENTO>();
            this.COMPRA_FORNECEDOR_ITEM = new HashSet<COMPRA_FORNECEDOR_ITEM>();
            this.COMPRA_ITEM = new HashSet<COMPRA_ITEM>();
            this.CRM_PEDIDO_VENDA_ITEM = new HashSet<CRM_PEDIDO_VENDA_ITEM>();
            this.CRM_PEDIDO_VENDA_ITEM_PECA = new HashSet<CRM_PEDIDO_VENDA_ITEM_PECA>();
            this.FICHA_TECNICA = new HashSet<FICHA_TECNICA>();
            this.FICHA_TECNICA_DETALHE = new HashSet<FICHA_TECNICA_DETALHE>();
            this.FORNECEDOR_PRODUTO = new HashSet<FORNECEDOR_PRODUTO>();
            this.MOVIMENTO_ESTOQUE_PRODUTO = new HashSet<MOVIMENTO_ESTOQUE_PRODUTO>();
            this.ORDEM_SERVICO = new HashSet<ORDEM_SERVICO>();
            this.ORDEM_SERVICO_PRODUTO = new HashSet<ORDEM_SERVICO_PRODUTO>();
            this.PRECIFICACAO = new HashSet<PRECIFICACAO>();
            this.PRECIFICACAO_PRODUTO = new HashSet<PRECIFICACAO_PRODUTO>();
            this.PRODUTO_ANOTACAO = new HashSet<PRODUTO_ANOTACAO>();
            this.PRODUTO_CONCORRENTE = new HashSet<PRODUTO_CONCORRENTE>();
            this.PRODUTO_CUSTO = new HashSet<PRODUTO_CUSTO>();
            this.PRODUTO_ESTOQUE_FILIAL = new HashSet<PRODUTO_ESTOQUE_FILIAL>();
            this.PRODUTO_ESTOQUE_HISTORICO = new HashSet<PRODUTO_ESTOQUE_HISTORICO>();
            this.PRODUTO_KIT = new HashSet<PRODUTO_KIT>();
            this.PRODUTO_KIT1 = new HashSet<PRODUTO_KIT>();
            this.PRODUTO_LOG = new HashSet<PRODUTO_LOG>();
            this.PRODUTO_PRECO_VENDA = new HashSet<PRODUTO_PRECO_VENDA>();
            this.SERVICOS_PECA = new HashSet<SERVICOS_PECA>();
            this.PRODUTO_ANEXO = new HashSet<PRODUTO_ANEXO>();
            this.LOCACAO = new HashSet<LOCACAO>();
            this.AVISO_LEMBRETE = new HashSet<AVISO_LEMBRETE>();
            this.PACIENTE_CONSULTA_MATERIAL = new HashSet<PACIENTE_CONSULTA_MATERIAL>();
            this.VALOR_CONSULTA_MATERIAL = new HashSet<VALOR_CONSULTA_MATERIAL>();
        }
    
        public int PROD_CD_ID { get; set; }
        public string PROD_NM_NOME { get; set; }
        public int PROD_IN_ATIVO { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> CAPR_CD_ID { get; set; }
        public Nullable<int> SCPR_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public Nullable<int> TIEM_CD_ID { get; set; }
        public Nullable<int> PROD_IN_USUARIO_ALTERACAO { get; set; }
        public Nullable<System.DateTime> PROD_DT_CADASTRO { get; set; }
        public Nullable<System.DateTime> PROD_DT_ALTERACAO { get; set; }
        public Nullable<int> PROD_IN_TIPO_PRODUTO { get; set; }
        public Nullable<int> PROD_IN_COMPOSTO { get; set; }
        public string PROD_AQ_FOTO { get; set; }
        public string PROD_CD_CODIGO { get; set; }
        public string PROD_NR_BARCODE { get; set; }
        public Nullable<int> PROD_IN_FRACIONADO { get; set; }
        public string PROD_DS_DESCRICAO { get; set; }
        public string PROD_DS_INFORMACOES { get; set; }
        public string PROD_NR_REFERENCIA { get; set; }
        public string PROD_NM_MARCA { get; set; }
        public string PROD_NM_MODELO { get; set; }
        public string PROD_NM_REFERENCIA_FABRICANTE { get; set; }
        public string PROD_NM_FABRICANTE { get; set; }
        public Nullable<decimal> PROD_VL_ESTOQUE_ATUAL { get; set; }
        public Nullable<decimal> PROD_VL_ESTOQUE_MAXIMO { get; set; }
        public Nullable<decimal> PROD_VL_ESTOQUE_MINIMO { get; set; }
        public Nullable<decimal> PROD_VL_ESTOQUE_RESERVA { get; set; }
        public Nullable<decimal> PROD_VL_MEDIA_VENDA_MENSAL { get; set; }
        public Nullable<decimal> PROD_VL_PRECO_VENDA { get; set; }
        public Nullable<decimal> PROD_VL_PRECO_PROMOCAO { get; set; }
        public Nullable<decimal> PROD_VL_CUSTO { get; set; }
        public Nullable<decimal> PROD_VL_CVM_RECEITA { get; set; }
        public Nullable<decimal> PROD_VL_CVM_UNITARIO { get; set; }
        public Nullable<decimal> PROD_VL_CVM_PESO { get; set; }
        public Nullable<decimal> PROD_VL_PRECO_MINIMO { get; set; }
        public Nullable<decimal> PROD_PC_DESCONTO { get; set; }
        public Nullable<decimal> PROD_VL_ULTIMO_CUSTO { get; set; }
        public Nullable<decimal> PROD_VL_PRECO_ANTERIOR { get; set; }
        public Nullable<decimal> PROD_VL_CUSTO_CONCORRENTE_MEDIO { get; set; }
        public Nullable<decimal> PROD_VL_MARGEM_CONTRIBUICAO { get; set; }
        public Nullable<decimal> PROD_VL_FATOR_CORRECAO { get; set; }
        public string PROD_TX_OBSERVACOES { get; set; }
        public Nullable<decimal> PROD_VL_ESTOQUE_CUSTO { get; set; }
        public Nullable<decimal> PROD_VL_ESTOQUE_VENDA { get; set; }
        public Nullable<int> PROD_IN_PECA { get; set; }
        public Nullable<decimal> PROD_VL_ESTOQUE_TOTAL { get; set; }
        public Nullable<int> PROD_IN_SISTEMA { get; set; }
        public string PROD_NM_FORNECEDOR { get; set; }
        public Nullable<int> PROD_IN_LOCACAO { get; set; }
        public Nullable<decimal> PROD_VL_LOCACAO { get; set; }
        public Nullable<decimal> PROD_VL_LOCACAO_PROMOCAO { get; set; }
        public Nullable<decimal> PROD_VL_LOCACAO_MULTA { get; set; }
        public Nullable<decimal> PROD_VL_LOCACAO_TAXAS { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENDIMENTO> ATENDIMENTO { get; set; }
        public virtual CATEGORIA_PRODUTO CATEGORIA_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_FORNECEDOR_ITEM> COMPRA_FORNECEDOR_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_ITEM> COMPRA_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_PEDIDO_VENDA_ITEM> CRM_PEDIDO_VENDA_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_PEDIDO_VENDA_ITEM_PECA> CRM_PEDIDO_VENDA_ITEM_PECA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHA_TECNICA> FICHA_TECNICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHA_TECNICA_DETALHE> FICHA_TECNICA_DETALHE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORNECEDOR_PRODUTO> FORNECEDOR_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMENTO_ESTOQUE_PRODUTO> MOVIMENTO_ESTOQUE_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO> ORDEM_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEM_SERVICO_PRODUTO> ORDEM_SERVICO_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRECIFICACAO> PRECIFICACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRECIFICACAO_PRODUTO> PRECIFICACAO_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_ANOTACAO> PRODUTO_ANOTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_CONCORRENTE> PRODUTO_CONCORRENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_CUSTO> PRODUTO_CUSTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_ESTOQUE_FILIAL> PRODUTO_ESTOQUE_FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_ESTOQUE_HISTORICO> PRODUTO_ESTOQUE_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_KIT> PRODUTO_KIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_KIT> PRODUTO_KIT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_LOG> PRODUTO_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_PRECO_VENDA> PRODUTO_PRECO_VENDA { get; set; }
        public virtual SUBCATEGORIA_PRODUTO SUBCATEGORIA_PRODUTO { get; set; }
        public virtual TIPO_EMBALAGEM TIPO_EMBALAGEM { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICOS_PECA> SERVICOS_PECA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_ANEXO> PRODUTO_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCACAO> LOCACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVISO_LEMBRETE> AVISO_LEMBRETE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_CONSULTA_MATERIAL> PACIENTE_CONSULTA_MATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALOR_CONSULTA_MATERIAL> VALOR_CONSULTA_MATERIAL { get; set; }
    }
}
