//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTIONARIO_STOPBANG
    {
        public int QUSB_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int PACI_CD_ID { get; set; }
        public Nullable<int> QUSB_IN_RONCO { get; set; }
        public Nullable<int> QUSB_IN_CANSADO { get; set; }
        public Nullable<int> QUSB_IN_OBSERVA { get; set; }
        public Nullable<int> QUSB_IN_PRESSAO { get; set; }
        public Nullable<int> QUSB_IN_PESCOCO { get; set; }
        public Nullable<int> QUSB_IN_IMC { get; set; }
        public Nullable<int> QUSB_IN_IDADE { get; set; }
        public Nullable<int> QUSB_IN_MASCULINO { get; set; }
        public string QUSB_DS_PONTUACAO { get; set; }
        public Nullable<int> QUSB_IN_ATIVO { get; set; }
        public Nullable<int> QUSB_IN_PONTUACAO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
