//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEBIMENTO_RECIBO
    {
        public int RERC_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int CORE_CD_ID { get; set; }
        public string RERC_NR_NUMERO { get; set; }
        public Nullable<System.DateTime> RERC_DT_EMISSAO { get; set; }
        public Nullable<decimal> RERC_VL_VALOR { get; set; }
        public string RERC_NM_NOME { get; set; }
        public string RERC_DS_DESCRICAO { get; set; }
        public string RERC_NM_PACIENTE { get; set; }
        public string RERC_NR_CPF { get; set; }
        public string RERC_NM_MEDICO { get; set; }
        public string RERC_CPF_MEDICO { get; set; }
        public string RERC_NR_CLASSE { get; set; }
        public string RERC_SG_UF { get; set; }
        public string RERC_NM_ESPECIALIDADE { get; set; }
        public string RERC_NM_ENDERECO { get; set; }
        public string RERC_NM_FORMA_PAGTO { get; set; }
        public string RERC_SG_ASSINATURA_TIPO { get; set; }
        public string RERC_DS_ASSINATURA { get; set; }
        public Nullable<int> RERC_IN_ATIVO { get; set; }
        public string RERC_AQ_ARQUIVO { get; set; }
        public string RERC_NR_CPF_MEDICO { get; set; }
    
        public virtual CONSULTA_RECEBIMENTO CONSULTA_RECEBIMENTO { get; set; }
    }
}
