//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEBIMENTO_ANOTACAO
    {
        public int REAT_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> CORE_CD_ID { get; set; }
        public Nullable<System.DateTime> REAT_DT_ANOTACAO { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public string REAT_TX_ANOTACAO { get; set; }
        public Nullable<int> REAT_IN_ATIVO { get; set; }
    
        public virtual CONSULTA_RECEBIMENTO CONSULTA_RECEBIMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
