//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECURSIVIDADE_GERAL_DATA
    {
        public int REGT_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> REGE_CD_ID { get; set; }
        public Nullable<System.DateTime> REGT_DT_PROGRAMADA { get; set; }
        public Nullable<int> REGT_IN_PROCESSADA { get; set; }
        public Nullable<int> REGT_IN_ATIVO { get; set; }
    }
}
