//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADO_ROBOT_CUSTO
    {
        public int RERC_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int CUFX_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int RERC_IN_TIPO { get; set; }
        public string RERC_DS_MENSAGEM { get; set; }
        public System.DateTime RERC_DT_ENVIO { get; set; }
        public string RERC_NM_DESTINO { get; set; }
        public string RERC_NR_CELULAR { get; set; }
        public string RERC_NM_EMAIL { get; set; }
        public int RERC_IN_ATIVO { get; set; }
        public string RERC_SG_ID { get; set; }
        public string RERC_NM_STATUS { get; set; }
        public Nullable<int> RERC_IN_STATUS { get; set; }
        public Nullable<System.DateTime> RERC_DT_DUMMY { get; set; }
        public string RERC_NM_BUSCA { get; set; }
        public string RERC_GU_ID_MENSAGEM { get; set; }
    
        public virtual CUSTO_FIXO CUSTO_FIXO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
