//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICOS_CONCORRENTE
    {
        public int SEPF_CD_ID { get; set; }
        public int SERV_CD_ID { get; set; }
        public string SEPF_NM_CONCORRENTE { get; set; }
        public decimal SEPF_VL_PRECO_CONCORRENTE { get; set; }
        public int SEPF_IN_ATIVO { get; set; }
        public System.DateTime SEPF_DT_CADASTRO { get; set; }
        public Nullable<int> SEPF_IN_SISTEMA { get; set; }
    
        public virtual SERVICOS SERVICOS { get; set; }
    }
}
