//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICOS()
        {
            this.CRM_PEDIDO_VENDA_ITEM_SERVICO = new HashSet<CRM_PEDIDO_VENDA_ITEM_SERVICO>();
            this.SERVICOS_ANOTACAO = new HashSet<SERVICOS_ANOTACAO>();
            this.SERVICOS_CONCORRENTE = new HashSet<SERVICOS_CONCORRENTE>();
            this.SERVICOS_CUSTO = new HashSet<SERVICOS_CUSTO>();
            this.SERVICOS_LOG = new HashSet<SERVICOS_LOG>();
            this.SERVICOS_PECA = new HashSet<SERVICOS_PECA>();
            this.SERVICOS_PRECO_VENDA = new HashSet<SERVICOS_PRECO_VENDA>();
            this.SERVICOS_ANEXO = new HashSet<SERVICOS_ANEXO>();
        }
    
        public int SERV_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> CASE_CD_ID { get; set; }
        public Nullable<int> NBSE_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public Nullable<int> SERV_IN_SERVICO_ALTERACAO { get; set; }
        public Nullable<System.DateTime> SERV_DT_CADASTRO { get; set; }
        public Nullable<System.DateTime> SERV_DT_ALTERACAO { get; set; }
        public Nullable<int> SERV_IN_TIPO_PRODUTO { get; set; }
        public string SERV_AQ_FOTO { get; set; }
        public string SERV_CD_CODIGO { get; set; }
        public string SERV_NR_BARCODE { get; set; }
        public string SERV_NM_NOME { get; set; }
        public string SERV_DS_DESCRICAO { get; set; }
        public string SERV_DS_INFORMACOES { get; set; }
        public Nullable<decimal> SERV_VL_PRECO_VENDA { get; set; }
        public Nullable<decimal> SERV_VL_PRECO_PROMOCAO { get; set; }
        public Nullable<decimal> SERV_VL_CUSTO { get; set; }
        public Nullable<decimal> SERV_VL_PRECO_MINIMO { get; set; }
        public Nullable<decimal> SERV_PC_DESCONTO { get; set; }
        public Nullable<decimal> SERV_VL_ULTIMO_CUSTO { get; set; }
        public Nullable<decimal> SERV_VL_PRECO_ANTERIOR { get; set; }
        public Nullable<decimal> SERV_VL_CUSTO_CONCORRENTE_MEDIO { get; set; }
        public Nullable<int> SERV_NR_DURACAO { get; set; }
        public Nullable<int> SERV_NR_DURACAO_EXPRESSA { get; set; }
        public Nullable<decimal> SERV_VL_PRECO_EXPRESSO { get; set; }
        public Nullable<int> SERV_IN_LOCAL { get; set; }
        public Nullable<decimal> SERV_VL_VISITA { get; set; }
        public string SERV_TX_OBSERVACOES { get; set; }
        public int SERV_IN_ATIVO { get; set; }
        public Nullable<int> SERV_IN_SISTEMA { get; set; }
    
        public virtual CATEGORIA_SERVICO CATEGORIA_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_PEDIDO_VENDA_ITEM_SERVICO> CRM_PEDIDO_VENDA_ITEM_SERVICO { get; set; }
        public virtual NOMENCLATURA_BRAS_SERVICOS NOMENCLATURA_BRAS_SERVICOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICOS_ANOTACAO> SERVICOS_ANOTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICOS_CONCORRENTE> SERVICOS_CONCORRENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICOS_CUSTO> SERVICOS_CUSTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICOS_LOG> SERVICOS_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICOS_PECA> SERVICOS_PECA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICOS_PRECO_VENDA> SERVICOS_PRECO_VENDA { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICOS_ANEXO> SERVICOS_ANEXO { get; set; }
    }
}
