//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICO_TABELA_PRECO
    {
        public int SETP_CD_ID { get; set; }
        public int SERV_CD_ID { get; set; }
        public int FILI_CD_ID { get; set; }
        public Nullable<decimal> SETP_VL_PRECO { get; set; }
        public Nullable<decimal> SETP_VL_PRECO_PROMOCAO { get; set; }
        public Nullable<decimal> SETP_VL_DESCONTO_MAXIMO { get; set; }
        public Nullable<System.DateTime> SETP_DT_DATA_REAJUSTE { get; set; }
        public int SETP_IN_ATIVO { get; set; }
        public Nullable<decimal> SETP_NR_MARKUP { get; set; }
        public Nullable<decimal> SETP_VL_CUSTO { get; set; }
    
        public virtual FILIAL FILIAL { get; set; }
        public virtual SERVICO SERVICO { get; set; }
    }
}
