//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICOS_ANOTACAO
    {
        public int SEAT_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public int SERV_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime SEAT_DT_ANOTACAO { get; set; }
        public string SEAT_DS_ANOTACAO { get; set; }
        public int SEAT_IN_ATIVO { get; set; }
        public Nullable<int> SEAT_IN_SISTEMA { get; set; }
    
        public virtual SERVICOS SERVICOS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
