//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITACAO
    {
        public int SOLI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int TIEX_CD_ID { get; set; }
        public string SOLI_NM_TITULO { get; set; }
        public string SOLI_NM_INDICACAO { get; set; }
        public string SOLI_DS_DESCRICAO { get; set; }
        public int SOLI_IN_ATIVO { get; set; }
    
        public virtual TIPO_EXAME TIPO_EXAME { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
