//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREFA_NOTIFICACAO
    {
        public int TANO_CD_ID { get; set; }
        public int TARE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int TANO_IN_ATIVO { get; set; }
    
        public virtual TAREFA TAREFA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
