//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREFA_ANEXO
    {
        public int TAAN_CD_ID { get; set; }
        public int TARE_CD_ID { get; set; }
        public string TAAN_NM_TITULO { get; set; }
        public Nullable<System.DateTime> TAAN_DT_ANEXO { get; set; }
        public Nullable<int> TAAN_IN_TIPO { get; set; }
        public string TAAN_AQ_ARQUIVO { get; set; }
        public int TAAN_IN_ATIVO { get; set; }
    
        public virtual TAREFA TAREFA { get; set; }
    }
}
