//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE_EMAIL_HTML
    {
        public int TEHT_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string TEHT_NM_NOME { get; set; }
        public string TEHT_AQ_ARQUIVO { get; set; }
        public Nullable<int> TEHT_IN_ATIVO { get; set; }
        public Nullable<int> TEHT_IN_SISTEMA { get; set; }
        public Nullable<System.DateTime> TEHT_DT_CADASTRO { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
