//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ATESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_ATESTADO()
        {
            this.PACIENTE_ATESTADO = new HashSet<PACIENTE_ATESTADO>();
        }
    
        public int TIAT_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public string TIAT_NM_NOME { get; set; }
        public Nullable<int> TIAT_IN_ATIVO { get; set; }
        public string TIAT_TX_TEXTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ATESTADO> PACIENTE_ATESTADO { get; set; }
    }
}
