//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_ACAO()
        {
            this.ATENDIMENTO_ACAO = new HashSet<ATENDIMENTO_ACAO>();
            this.CRM_ACAO = new HashSet<CRM_ACAO>();
            this.INDICACAO_ACAO = new HashSet<INDICACAO_ACAO>();
        }
    
        public int TIAC_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string TIAC_NM_NOME { get; set; }
        public Nullable<int> TIAC_IN_ATIVO { get; set; }
        public Nullable<int> TIAC_IN_TIPO { get; set; }
        public Nullable<int> TIAC_IN_SISTEMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENDIMENTO_ACAO> ATENDIMENTO_ACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_ACAO> CRM_ACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INDICACAO_ACAO> INDICACAO_ACAO { get; set; }
    }
}
