//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ENVIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_ENVIO()
        {
            this.MEDICOS_ENVIO = new HashSet<MEDICOS_ENVIO>();
        }
    
        public int TIEN_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string TIEN_NM_NOME { get; set; }
        public int TIEN_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICOS_ENVIO> MEDICOS_ENVIO { get; set; }
    }
}
