//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_HISTORICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_HISTORICO()
        {
            this.LOCACAO_HISTORICO = new HashSet<LOCACAO_HISTORICO>();
        }
    
        public int TIHI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string TIHI_NM_NOME { get; set; }
        public int TIHI_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCACAO_HISTORICO> LOCACAO_HISTORICO { get; set; }
    }
}
