//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ITEM_EXAME
    {
        public int TIIE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> TIIE_IN_TIPO { get; set; }
        public string TIIE_SG_SIGLA { get; set; }
        public string TIIE_DS_DESCRICAO { get; set; }
        public int TIIE_IN_ATIVO { get; set; }
    }
}
