//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_EMBALAGEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_EMBALAGEM()
        {
            this.PRODUTO = new HashSet<PRODUTO>();
            this.PRODUTO_PRECO_VENDA = new HashSet<PRODUTO_PRECO_VENDA>();
        }
    
        public int TIEM_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public string TIEM_NM_NOME { get; set; }
        public string TIEM_DS_DESCRICAO { get; set; }
        public Nullable<int> TIEM_NR_ALTURA { get; set; }
        public Nullable<int> TIEM_NR_LARGURA { get; set; }
        public Nullable<int> TIEM_NR_COMPRIMENTO { get; set; }
        public Nullable<int> TIEM_NR_DIAMETRO { get; set; }
        public Nullable<decimal> TIIEM_VL_CUSTO_UNITARIO { get; set; }
        public Nullable<int> TIEM_NR_ESTOQUE { get; set; }
        public Nullable<int> TIEM_ESTOQUE_INICIAL { get; set; }
        public Nullable<decimal> TIEM_VLCUSTO_REPASSADO { get; set; }
        public Nullable<int> TIEM_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO> PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_PRECO_VENDA> PRODUTO_PRECO_VENDA { get; set; }
    }
}
