//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_VALOR_CONSULTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_VALOR_CONSULTA()
        {
            this.VALOR_CONSULTA = new HashSet<VALOR_CONSULTA>();
        }
    
        public int TIVL_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string TIVL_NM_TIPO { get; set; }
        public int TIVL_IN_ATIVO { get; set; }
        public Nullable<int> TIVL_IN_PADRAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALOR_CONSULTA> VALOR_CONSULTA { get; set; }
    }
}
