//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTADORA_ANEXO
    {
        public int TRAT_CD_ID { get; set; }
        public int TRAN_CD_ID { get; set; }
        public Nullable<System.DateTime> TRAT_DT_ANEXO { get; set; }
        public string TRAT_NM_TITULO { get; set; }
        public Nullable<int> TRAT_IN_TIPO { get; set; }
        public string TRAT_AQ_ARQUIVO { get; set; }
        public Nullable<int> TRAT_IN_ATIVO { get; set; }
    
        public virtual TRANSPORTADORA TRANSPORTADORA { get; set; }
    }
}
