//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTADORA_CONTATO
    {
        public int TRCO_CD_ID { get; set; }
        public int TRAN_CD_ID { get; set; }
        public string TRCO_NM_NOME { get; set; }
        public string TRCO_NM_CARGO { get; set; }
        public string TRCO_NR_TELEFONE { get; set; }
        public string TRCO_NR_CELULAR { get; set; }
        public string TRCO_NR_WHATSAPP { get; set; }
        public string TRCO_EM_EMAIL { get; set; }
        public Nullable<int> TRCO_IN_ATIVO { get; set; }
    
        public virtual TRANSPORTADORA TRANSPORTADORA { get; set; }
    }
}
