//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_ANOTACAO
    {
        public int USAN_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int USAN_CD_AUTOR { get; set; }
        public System.DateTime USAN_DT_ANOTACAO { get; set; }
        public string USAN_TX_ANOTACAO { get; set; }
        public int USAN_IN_ATIVO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
