//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALOR_CONVENIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VALOR_CONVENIO()
        {
            this.CONSULTA_RECEBIMENTO = new HashSet<CONSULTA_RECEBIMENTO>();
        }
    
        public int VACV_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> CONV_CD_ID { get; set; }
        public Nullable<System.DateTime> VACV_DT_REFERENCIA { get; set; }
        public Nullable<decimal> VACV_NR_VALOR { get; set; }
        public Nullable<int> VACV_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTA_RECEBIMENTO> CONSULTA_RECEBIMENTO { get; set; }
        public virtual CONVENIO CONVENIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
