//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALOR_CONSULTA_MATERIAL
    {
        public int VCMA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int VACO_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public Nullable<decimal> VCMA_QN_QUANTIDADE { get; set; }
        public int VCMA_IN_ATIVO { get; set; }
    
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual VALOR_CONSULTA VALOR_CONSULTA { get; set; }
    }
}
