//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULO
    {
        public int VEIC_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public int TRAN_CD_ID { get; set; }
        public int TIVE_CD_ID { get; set; }
        public int VEFU_CD_ID { get; set; }
        public string VEIC_NM_MARCA { get; set; }
        public string VEIC_NM_MODELO { get; set; }
        public Nullable<int> VEIC_NR_CAPACIDADE { get; set; }
        public string VEIC_NR_PLACA { get; set; }
        public Nullable<int> VEIC_IN_ATIVO { get; set; }
    
        public virtual TIPO_VEICULO TIPO_VEICULO { get; set; }
        public virtual TRANSPORTADORA TRANSPORTADORA { get; set; }
        public virtual VEICULO_FUNCAO VEICULO_FUNCAO { get; set; }
    }
}
