//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDA_MENSAL_CALCULO
    {
        public int VMCA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> VMCA_DT_CALCULO { get; set; }
        public Nullable<decimal> VMCA_VL_TOTAL { get; set; }
        public Nullable<decimal> VMCA_VL_VENDEDOR { get; set; }
        public Nullable<decimal> VMCA_VL_GERENTE { get; set; }
        public Nullable<decimal> VMCA_VL_OUTROS { get; set; }
        public Nullable<int> VMCA_IN_ATIVO { get; set; }
        public Nullable<int> EMFI_CD_ID { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual EMPRESA_FILIAL EMPRESA_FILIAL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
