//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO_BASE
    {
        public int VIDE_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> TIVE_CD_ID { get; set; }
        public Nullable<System.DateTime> VIDE_DT_INCLUSAO { get; set; }
        public string VIDE_NM_TITULO { get; set; }
        public string VIDE_AQ_ARQUIVO { get; set; }
        public Nullable<int> VIDE_IN_ATIVO { get; set; }
        public string VIDE_DS_DESCRICAO { get; set; }
    
        public virtual TIPO_VIDEO TIPO_VIDEO { get; set; }
    }
}
