//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO_COMENTARIO
    {
        public int VICO_CD_ID { get; set; }
        public int VIDE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime VICO_DT_COMENTARIO { get; set; }
        public string VICO_TX_COMENTARIO { get; set; }
        public int VICO_IN_ATIVO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual VIDEO VIDEO { get; set; }
    }
}
