using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EntitiesServices.Model;
using EntitiesServices.WorkClasses;

namespace EntitiesServices.Work_Classes
{
    public static class SessionMocks
    {
        public static USUARIO UserCredentials { get; set; }
        public static Int32 IdAssinante { get; set; }
        public static Int32 IdAssinanteVolta { get; set; }
        public static Int32 idCliente { get; set; }
        public static ASSINANTE Assinante { get; set; }
        public static List<USUARIO> listaUsuario { get; set; }
        public static USUARIO Usuario { get; set; }
        public static String NomeLogado { get; set; }
        public static List<LOG> listaLog { get; set; }
        public static Int32 Logs { get; set; }
        public static List<PERFIL> listaPerfil { get; set; }
        public static String voltaLogin { get; set; }
        public static String origem { get; set; }
        public static Int32 idVolta { get; set; }
        public static Int32 idVoltaTab { get; set; }
        public static Int32 idBanco { get; set; }
        public static String arquivo { get; set; }
        public static COLABORADOR Colaborador { get; set; }
        public static CONFIGURACAO Configuracao { get; set; }
        public static List<BANCO> listaBanco { get; set; }
        public static List<TIPO_CONTA> listaTipoConta { get; set; }
        public static List<CONTA_BANCO> listaContaBancaria { get; set; }
        public static BANCO banco { get; set; }
        public static Int32? IdMatriz { get; set; }
        public static MATRIZ Matriz { get; set; }
        public static List<FILIAL> listaFilial { get; set; }
        public static List<CLIENTE> listaCliente { get; set; }
        public static CLIENTE cliente { get; set; }
        public static Int32 voltaCliente { get; set; }
        public static List<FORNECEDOR> listaFornecedor { get; set; }
        public static FORNECEDOR fornecedor { get; set; }
        public static Int32 voltaFornecedor { get; set; }
        public static List<PRODUTO> listaProduto { get; set; }
        public static PRODUTO produto { get; set; }
        public static Int32 voltaProduto { get; set; }
        public static LOG filtroLog { get; set; }
        public static List<MATERIA_PRIMA> listaMateria { get; set; }
        public static MATERIA_PRIMA materiaPrima { get; set; }
        public static Int32 voltaMateria { get; set; }
        public static MATERIA_PRIMA filtroMateria { get; set; }
        public static CLIENTE filtroCliente { get; set; }
        public static FORNECEDOR filtroFornecedor { get; set; }
        public static PRODUTO filtroProduto { get; set; }
        public static USUARIO filtroUsuario { get; set; }
        public static List<SERVICO> listaServico { get; set; }
        public static SERVICO servico { get; set; }
        public static Int32 voltaSevico { get; set; }
        public static SERVICO filtroServico { get; set; }
        public static List<TRANSPORTADORA> listaTransportadora { get; set; }
        public static TRANSPORTADORA transportadora { get; set; }
        public static Int32 voltaTransportadora { get; set; }
        public static TRANSPORTADORA filtroTransportadora { get; set; }
        public static List<PATRIMONIO> listaPatrimonio { get; set; }
        public static PATRIMONIO patrimonio { get; set; }
        public static Int32 voltaPatrimonio { get; set; }
        public static PATRIMONIO filtroPatrimonio { get; set; }
        public static List<EQUIPAMENTO> listaEquipamento { get; set; }
        public static EQUIPAMENTO equipamento { get; set; }
        public static Int32 voltaEquipamento { get; set; }
        public static Int32 voltaCEP { get; set; }
        public static EQUIPAMENTO filtroEquipamento { get; set; }
        public static List<CARGO> listaCargo { get; set; }
        public static CARGO cargo { get; set; }
        public static CARGO filtroCargo { get; set; }
        public static List<VALOR_COMISSAO> listaComissao { get; set; }
        public static VALOR_COMISSAO comissao { get; set; }
        public static VALOR_COMISSAO filtroComissao { get; set; }
        public static Int32 clonar { get; set; }
        public static List<CONTRATO> listaContrato { get; set; }
        public static CONTRATO filtroContrato { get; set; }
        public static Int32 voltaContrato { get; set; }
        public static CONTRATO contrato { get; set; }
        public static Int32 voltaConta { get; set; }
        public static List<NOTICIA> listaNoticia { get; set; }
        public static List<NOTIFICACAO> listaNotificacao { get; set; }
        public static List<FICHA_TECNICA> listaFT { get; set; }
        public static FICHA_TECNICA fichaTecnica { get; set; }
        public static Int32 voltaFT { get; set; }
        public static FICHA_TECNICA filtroFT { get; set; }
        public static Int32 contratoAtraso { get; set; }
        public static CONTA_RECEBER cr { get; set; }
        public static Int32 idCRVolta { get; set; }
        public static Int32 emailEnviado { get; set; }
        public static Int32 voltaConsulta { get; set; }
        public static List<CONTA_RECEBER> listaRec { get; set; }
        public static List<CONTA_PAGAR> listaPag { get; set; }
        public static List<CATEGORIA_PRODUTO> listaCatProd { get; set; }
        public static CATEGORIA_PRODUTO catProduto { get; set; }
        public static Int32 voltaCatProd { get; set; }
        public static List<CATEGORIA_MATERIA> listaCatMat { get; set; }
        public static CATEGORIA_MATERIA catMateria { get; set; }
        public static Int32 voltaCatMat { get; set; }
        public static List<SUBCATEGORIA_PRODUTO> listaSubCatProd { get; set; }
        public static SUBCATEGORIA_PRODUTO subCatProduto { get; set; }
        public static Int32 voltaSubCatProd { get; set; }
        //public static List<SUBCATEGORIA_MATERIA> listaSubCatMat { get; set; }
        //public static SUBCATEGORIA_MATERIA subCatMateria { get; set; }
        public static Int32 voltaSubCatMat { get; set; }
        public static List<CATEGORIA_CLIENTE> listaCatCli { get; set; }
        public static CATEGORIA_CLIENTE catCliente { get; set; }
        public static Int32 voltaCatCli { get; set; }
        public static List<CATEGORIA_FORNECEDOR> listaCatFor { get; set; }
        public static CATEGORIA_FORNECEDOR catFornecedor { get; set; }
        public static Int32 voltaCatFor { get; set; }
        public static Int32 voltaPop { get; set; }
        public static List<CATEGORIA_CONTRATO> listaCatCont { get; set; }
        public static CATEGORIA_CONTRATO catContrato { get; set; }
        public static Int32 voltaCatCont { get; set; }
        public static List<FORMA_PAGAMENTO> listaForma { get; set; }
        public static FORMA_PAGAMENTO forma { get; set; }
        public static Int32 voltaForma { get; set; }
        public static List<PERIODICIDADE> listaPeriod { get; set; }
        public static PERIODICIDADE period { get; set; }
        public static Int32 voltaPeriod { get; set; }
        public static List<SEXO> listaSexo { get; set; }
        public static SEXO sexo { get; set; }
        public static Int32 voltaSexo { get; set; }
        public static List<TIPO_CONTRATO> listaTipoCont { get; set; }
        public static TIPO_CONTRATO tipoContrato { get; set; }
        public static Int32 voltaTipoCont { get; set; }
        public static List<TAMANHO> listaTamanho { get; set; }
        public static TAMANHO tamanho { get; set; }
        public static Int32 voltaTamanho { get; set; }
        public static List<TIPO_PESSOA> listaTipoPessoa { get; set; }
        public static TIPO_PESSOA tipoPessoa { get; set; }
        public static Int32 voltaTipoPessoa { get; set; }
        public static List<CATEGORIA_EQUIPAMENTO> listaCatEquip { get; set; }
        public static CATEGORIA_EQUIPAMENTO catEquip { get; set; }
        public static Int32 voltaCatEquip { get; set; }
        public static List<REGIME_TRIBUTARIO> listaRegTrib { get; set; }
        public static REGIME_TRIBUTARIO regTrib { get; set; }
        public static Int32 voltaRegTrib { get; set; }
        public static List<UNIDADE> listaUnidade { get; set; }
        public static UNIDADE unidade { get; set; }
        public static Int32 voltaUnidade { get; set; }
        public static List<TEMPLATE> listaTemplate { get; set; }
        public static TEMPLATE template { get; set; }
        public static Int32 voltaTemplate { get; set; }
        public static List<CONTA_RECEBER> listaCR { get; set; }
        public static CONTA_RECEBER contaReceber { get; set; }
        public static Int32 voltaCR { get; set; }
        public static CONTA_RECEBER filtroCR { get; set; }
        public static List<CONTA_PAGAR> listaCP { get; set; }
        public static CONTA_PAGAR contaPagar { get; set; }
        public static Int32 voltaCP { get; set; }
        public static CONTA_PAGAR filtroCP { get; set; }
        public static List<CONTA_RECEBER_PARCELA> listaCRP { get; set; }
        public static CONTA_RECEBER_PARCELA contaReceberParcela { get; set; }
        public static Int32 voltaCRP { get; set; }
        public static CONTA_RECEBER_PARCELA filtroCRP { get; set; }
        public static Int32 idVoltaCRP { get; set; }
        public static List<CONTA_RECEBER_TAG> listaCRT { get; set; }
        public static CONTA_RECEBER_TAG contaReceberTag { get; set; }
        public static Int32 voltaCRT { get; set; }
        public static Int32 idVoltaCRT { get; set; }
        public static Int32 liquidaCR { get; set; }
        public static Int32 liquidaCP { get; set; }
        public static CONTA_PAGAR_PARCELA contaPagarParcela { get; set; }
        public static Int32 idVoltaCPP { get; set; }
        public static List<CONTA_PAGAR_PARCELA> listaCPP { get; set; }
        public static Int32 eParcela { get; set; }
        public static List<CONTA_BANCO> listaCaixa { get; set; }
        public static CONTA_BANCO contaPadrao { get; set; }
        public static Int32 mesCaixa { get; set; }
        public static Int32 anoCaixa { get; set; }
        public static Int32 trocaConta { get; set; }
        public static DateTime dataReferencia { get; set; }
        public static CONTA_BANCO filtroCB { get; set; }
        public static Int32 diaCaixa { get; set; }
        public static Int32 tipoFiltro { get; set; }
        public static DateTime dataInicio { get; set; }
        public static DateTime dataFinal { get; set; }
        public static Int32 tipoFiltro1 { get; set; }
        public static Int32 tipoFiltro2 { get; set; }
        public static Int32 tipoFiltro3 { get; set; }
        public static Int32 tipoFiltro4 { get; set; }
        public static List<TAREFA> listaTarefa { get; set; }
        public static TAREFA filtroTarefa { get; set; }
        public static Int32 voltaTarefa { get; set; }
        public static TAREFA tarefa { get; set; }
        public static String Greeting { get; set; }
        public static String Nome { get; set; }
        public static String Cargo { get; set; }
        public static String Foto { get; set; }
        public static List<NOTIFICACAO> Notificacoes { get; set; }
        public static List<NOTICIA> Noticias { get; set; }
        public static Int32 NoticiasNumero { get; set; }
        public static Int32 TarefasPendentes { get; set; }
        public static Int32 Tarefas { get; set; }
        public static Int32 NovasNotificacoes { get; set; }
        public static List<TAREFA> TarefasLista { get; set; }
        public static List<PEDIDO_COMPRA> listaCompra { get; set; }
        public static PEDIDO_COMPRA pedidoCompra { get; set; }
        public static Int32 voltaCompra { get; set; }
        public static PERFIL perfil { get; set; }
        public static List<PEDIDO_VENDA> listaVenda { get; set; }
        public static PEDIDO_VENDA pedidoVenda { get; set; }
        public static Int32 voltaVenda { get; set; }
        public static Int32 PedidosTotal { get; set; }
        public static Int32 NumPedidosDia { get; set; }
        public static Int32 NumPedidosMes { get; set; }
        public static Int32 NumPedidosAno { get; set; }
        public static Decimal PedidosDia { get; set; }
        public static Decimal PedidosMes { get; set; }
        public static Decimal PedidosAno { get; set; }
        public static Int32 CPTotal { get; set; }
        public static Decimal CPDia { get; set; }
        public static Decimal CPMes { get; set; }
        public static Decimal CPAno { get; set; }
        public static Int32 CRTotal { get; set; }
        public static Decimal CRDia { get; set; }
        public static Decimal CRMes { get; set; }
        public static Decimal CRAno { get; set; }
        public static Decimal CaixaDia { get; set; }
        public static Decimal CaixaMes { get; set; }
        public static Decimal CaixaAno { get; set; }
        public static Int32 flagInicial { get; set; }
        public static Decimal estoqueProd { get; set; }
        public static Decimal estoqueInsumo { get; set; }
        public static Int32 ProdPontoPedido { get; set; }
        public static Int32 ProdEstoqueZerado { get; set; }
        public static Int32 flagVoltaProd { get; set; }
        public static Int32 InsPontoPedido { get; set; }
        public static Int32 InsEstoqueZerado { get; set; }
        public static Int32 flagVoltaIns { get; set; }
        public static Int32 filtroData { get; set; }
        public static Int32 filtroStatus { get; set; }
        public static List<RESUMO_VENDA> listaResumos { get; set; }
        public static Int32 numeroTotal { get; set; }
        public static Decimal valorTotal { get; set; }
        public static Int32 tipoAssinante { get; set; }
        public static ASSINANTE assinante { get; set; }
        public static List<PERFIL> Perfis { get; set; }
        public static List<CARGO> Cargos { get; set; }
        public static Int32 numUsuarios { get; set; }
        public static List<USUARIO> Usuarios { get; set; }
        public static List<ASSINANTE> listaAssinante { get; set; }
        public static Int32 voltaAssinante { get; set; }
        public static List<FILIAL> Filiais { get; set; }
        public static List<TIPO_CONTA> TipoContas { get; set; }
        public static List<CATEGORIA_CLIENTE> CatsClientes { get; set; }
        public static List<UF> UFs { get; set; }
        public static List<TIPO_CONTRIBUINTE> TiposContribuintes { get; set; }
        public static List<TIPO_PESSOA> TiposPessoas { get; set; }
        public static List<CENTRO_CUSTO> CentroCustos { get; set; }
        public static List<REGIME_TRIBUTARIO> Regimes { get; set; }
        public static List<UNIDADE> Unidades { get; set; }
        public static List<FORMA_PAGAMENTO> Formas { get; set; }
        public static List<PERIODICIDADE> Periodicidades { get; set; }
        public static List<CATEGORIA_FORNECEDOR> CatsForns { get; set; }
        public static List<SITUACAO> Situacoes { get; set; }
        public static List<FUNCAO> Funcoes { get; set; }
        public static List<SEXO> Sexos { get; set; }
        public static List<ESCOLARIDADE> Escolaridades { get; set; }
        public static List<CATEGORIA_MATERIA> CatsInsumos { get; set; }
        public static List<CATEGORIA_PATRIMONIO> CatsPatrimonio { get; set; }
        public static List<CATEGORIA_PRODUTO> CatsProduto { get; set; }
        public static List<CENTRO_CUSTO> listaCC { get; set; }
        public static CENTRO_CUSTO ccusto { get; set; }
        public static List<FORNECEDOR> Fornecedores { get; set; }
        public static List<PRODUTO> Produtos { get; set; }
        public static List<MATERIA_PRIMA> Insumos { get; set; }
        public static List<CONTA_BANCO> ContasBancarias { get; set; }
        public static Int32 idCPVolta { get; set; }
        public static List<CLIENTE> Clientes { get; set; }
        public static List<PRODUTO> pontoPedidoProd { get; set; }
        public static List<PRODUTO> estoqueZeradoProd { get; set; }
        public static List<PRODUTO> estoqueNegativoProd { get; set; }
        public static List<FUNCIONARIO> listaFunc { get; set; }
        public static Int32 voltaFunc { get; set; }
        public static FUNCIONARIO funcionario { get; set; }
        public static List<MATERIA_PRIMA> pontoPedidoIns { get; set; }
        public static List<MATERIA_PRIMA> estoqueZeradoIns { get; set; }
        public static List<MATERIA_PRIMA> estoqueNegativoIns { get; set; }
        public static Int32 voltaNoticia { get; set; }
        public static NOTICIA noticia { get; set; }
        public static NOTIFICACAO notificacao { get; set; }
        public static Int32 idFilial { get; set; }
        public static List<AGENDA> listaAgenda { get; set; }
        public static List<AGENDA> listaAgendaTimeline { get; set; }
        public static List<AGENDA> listaAgendaCalendario { get; set; }
        public static AGENDA agenda { get; set; }
        public static List<CATEGORIA_AGENDA> CatsAgenda { get; set; }
        public static Int32 voltaAgenda { get; set; }
        public static List<AGENDA> Agendas { get; set; }
        public static List<AGENDA> AgendasHoje { get; set; }
        public static Int32 numAgendas { get; set; }
        public static Int32 numAgendasHoje { get; set; }
        public static Int32 numEquipamentos{ get; set; }
        public static List<EQUIPAMENTO> listaManutencaoVencida { get; set; }
        public static Int32? idProduto { get; set; }
        public static Int32 VoltaComposto { get; set; }
        public static Int32 estoqueProdMinimo { get; set; }
        public static Int32 estoqueInsMinimo { get; set; }
        public static List<NOTIFICACAO> listaNovas { get; set; }
        public static List<TAREFA> listaPendentes { get; set; }
        public static List<TIPO_TAG> Tags { get; set; }
        public static List<ATENDIMENTO> listaAtendimento { get; set; }
        public static ATENDIMENTO atendimento { get; set; }
        public static Int32 voltaAtendimento { get; set; }
        public static Boolean voltaAcompanhamento { get; set; }
        public static List<ATENDIMENTO> listaHoje { get; set; }
        public static List<CATEGORIA_ATENDIMENTO> listaCatAten { get; set; }
        public static CATEGORIA_ATENDIMENTO catAten { get; set; }
        public static Int32 voltaOS { get; set; }
        public static Int32 consultaAtendimento { get; set; }
        public static Int32 idAtendimento { get; set; }
        public static List<ORDEM_SERVICO> listaOS { get; set; }
        public static ORDEM_SERVICO ordemServico { get; set; }
        public static Int32 voltaOrdemServico { get; set; }
        public static List<ORDEM_SERVICO> listaHojeOS { get; set; }
        public static Int32 consultaOS { get; set; }
        public static Int32 idOS { get; set; }
        public static ATENDIMENTO filtroAtendimento { get; set; }

        public static FUNCIONARIO filtroFunc { get; set; }
        public static AGENDA filtroAgenda { get; set; }
        public static List<CLIENTE> listaInativos{ get; set; }

        public static Boolean CategoriaToProduto { get; set; }
        public static Boolean SubCategoriaToProduto { get; set; }
        public static Boolean CategoriaToMateria { get; set; }
        public static Boolean SubCategoriaToMateria { get; set; }
        public static Boolean CategoriaToEquipamento { get; set; }
        public static List<CLIENTE> listaSemPedidos { get; set; }
        public static NOTIFICACAO filtroNotificacao { get; set; }
        public static List<DEPARTAMENTO> listaDepartamento { get; set; }
        public static Int32 voltaDepartamento { get; set; }
        public static DEPARTAMENTO departamento { get; set; }
        public static Int32 flagVoltaDept { get; set; }
        public static Int32 voltaCC { get; set; }
        public static CENTRO_CUSTO filtroCC { get; set; }
        public static Int32 flagVoltaCC { get; set; }
        public static SUBCATEGORIA_MATERIA subCatMateria { get; set; }
        public static List<SUBCATEGORIA_MATERIA> listaSubCatMat { get; set; }
        public static Int32? filtroInventario { get; set; }
        public static Int32? filtroAgendaCalendario { get; set; }
        public static Int32? voltaInventario { get; set; }
        public static List<MOVIMENTO_ESTOQUE_PRODUTO> listaMovimentoProduto { get; set; }
        public static List<MOVIMENTO_ESTOQUE_MATERIA_PRIMA> listaMovimentoInsumo { get; set; }
        public static MOVIMENTO_ESTOQUE_PRODUTO filtroMovimentoProduto { get; set; }
        public static MOVIMENTO_ESTOQUE_MATERIA_PRIMA filtroMovimentoInsumo { get; set; }
        public static Int32? filtroMovimentoEntrada { get; set; }
        public static Int32? filtroMovimentoSaida { get; set; }
        public static List<Hashtable> listaValEstoqueAlterado { get; set; }
        public static Int32? idAtendimentoAgenda { get; set; }
        public static String Error { get; set; }
        public static Boolean filtroMvmtProd { get; set; }
        public static Boolean filtroMvmtIns { get; set; }
        public static Int32? EntradaSaida { get; set; }
        public static Int32? flagMovmtAvulsa { get; set; }
        public static Boolean FornecedorToCp { get; set; }
        public static Boolean ClienteToCr { get; set; }
        public static Int32? voltaNotificacao { get; set; }
        public static Hashtable errosAgendamento { get; set; }
        public static Int32? pedidoRecebido { get; set; }
        public static Int32? smsEmailEnvio { get; set; }
        public static List<PRODUTOS_MAIS_VENDIDOS> ListProdMaisVendidos { get; set; }
        public static Int32? idCompra { get; set; }
        public static List<ITEM_PEDIDO_COMPRA> listaITPC { get; set; }
        public static List<PRODUTO_TABELA_PRECO> listaPrecoProduto { get; set; }
        public static PEDIDO_COMPRA filtroCompra { get; set; }
        public static Int32? voltaKanban { get; set; }
        public static List<FORNECEDOR> listaFornecedoresInativo { get; set; }
        public static List<FORNECEDOR> listaFornecedoresSemPedido { get; set; }
        public static List<MATERIA_PRIMA_PRECO> listaPrecoMateria { get; set; }
        public static List<EQUIPAMENTO> listaEquipamentoDepreciados { get; set; }
        public static List<EQUIPAMENTO> listaEquipamentoBaixados { get; set; }
    }
}
